// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for newrelicmysql metrics.
type MetricsConfig struct {
	NewrelicmysqlBytesReceived                MetricConfig `mapstructure:"newrelicmysql.bytes.received"`
	NewrelicmysqlBytesSent                    MetricConfig `mapstructure:"newrelicmysql.bytes.sent"`
	NewrelicmysqlCommands                     MetricConfig `mapstructure:"newrelicmysql.commands"`
	NewrelicmysqlConnections                  MetricConfig `mapstructure:"newrelicmysql.connections"`
	NewrelicmysqlConnectionsMax               MetricConfig `mapstructure:"newrelicmysql.connections.max"`
	NewrelicmysqlInnodbBufferPoolPagesData    MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool.pages.data"`
	NewrelicmysqlInnodbBufferPoolPagesFree    MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool.pages.free"`
	NewrelicmysqlInnodbBufferPoolReadRequests MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool.read_requests"`
	NewrelicmysqlInnodbBufferPoolReads        MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool.reads"`
	NewrelicmysqlInnodbRowLockTime            MetricConfig `mapstructure:"newrelicmysql.innodb.row_lock.time"`
	NewrelicmysqlInnodbRowLockWaits           MetricConfig `mapstructure:"newrelicmysql.innodb.row_lock.waits"`
	NewrelicmysqlQueries                      MetricConfig `mapstructure:"newrelicmysql.queries"`
	NewrelicmysqlSlowQueries                  MetricConfig `mapstructure:"newrelicmysql.slow_queries"`
	NewrelicmysqlThreadsRunning               MetricConfig `mapstructure:"newrelicmysql.threads.running"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		NewrelicmysqlBytesReceived: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlBytesSent: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlCommands: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlConnections: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlConnectionsMax: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolPagesData: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolPagesFree: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolReadRequests: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolReads: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbRowLockTime: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbRowLockWaits: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlQueries: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlSlowQueries: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlThreadsRunning: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for newrelicmysql resource attributes.
type ResourceAttributesConfig struct {
	MysqlInstanceEndpoint ResourceAttributeConfig `mapstructure:"mysql.instance.endpoint"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		MysqlInstanceEndpoint: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for newrelicmysql metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
