// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for newrelicmysql metrics.
type MetricsConfig struct {
	NewrelicmysqlBinlogCacheDiskUse                     MetricConfig `mapstructure:"newrelicmysql.binlog.cache_disk_use"`
	NewrelicmysqlBinlogCacheUse                         MetricConfig `mapstructure:"newrelicmysql.binlog.cache_use"`
	NewrelicmysqlCommands                               MetricConfig `mapstructure:"newrelicmysql.commands"`
	NewrelicmysqlConnectionCount                        MetricConfig `mapstructure:"newrelicmysql.connection.count"`
	NewrelicmysqlDbHandlerRollback                      MetricConfig `mapstructure:"newrelicmysql.db.handler_rollback"`
	NewrelicmysqlDbOpenedTables                         MetricConfig `mapstructure:"newrelicmysql.db.opened_tables"`
	NewrelicmysqlInnodbActiveTransactions               MetricConfig `mapstructure:"newrelicmysql.innodb.active_transactions"`
	NewrelicmysqlInnodbAdaptiveHashHashSearches         MetricConfig `mapstructure:"newrelicmysql.innodb.adaptive_hash_hash_searches"`
	NewrelicmysqlInnodbAdaptiveHashNonHashSearches      MetricConfig `mapstructure:"newrelicmysql.innodb.adaptive_hash_non_hash_searches"`
	NewrelicmysqlInnodbAdaptiveHashPagesAdded           MetricConfig `mapstructure:"newrelicmysql.innodb.adaptive_hash_pages_added"`
	NewrelicmysqlInnodbAdaptiveHashPagesRemoved         MetricConfig `mapstructure:"newrelicmysql.innodb.adaptive_hash_pages_removed"`
	NewrelicmysqlInnodbAvailableUndoLogs                MetricConfig `mapstructure:"newrelicmysql.innodb.available_undo_logs"`
	NewrelicmysqlInnodbBufferPoolBytesData              MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_bytes_data"`
	NewrelicmysqlInnodbBufferPoolBytesDirty             MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_bytes_dirty"`
	NewrelicmysqlInnodbBufferPoolDirty                  MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_dirty"`
	NewrelicmysqlInnodbBufferPoolFree                   MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_free"`
	NewrelicmysqlInnodbBufferPoolPagesData              MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_pages_data"`
	NewrelicmysqlInnodbBufferPoolPagesFlushed           MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_pages_flushed"`
	NewrelicmysqlInnodbBufferPoolPagesFree              MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_pages_free"`
	NewrelicmysqlInnodbBufferPoolPagesLruFlushed        MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_pages_lru_flushed"`
	NewrelicmysqlInnodbBufferPoolPagesMadeNotYoung      MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_pages_made_not_young"`
	NewrelicmysqlInnodbBufferPoolPagesMadeYoung         MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_pages_made_young"`
	NewrelicmysqlInnodbBufferPoolPagesMisc              MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_pages_misc"`
	NewrelicmysqlInnodbBufferPoolPagesOld               MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_pages_old"`
	NewrelicmysqlInnodbBufferPoolPagesTotal             MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_pages_total"`
	NewrelicmysqlInnodbBufferPoolReadAhead              MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_read_ahead"`
	NewrelicmysqlInnodbBufferPoolReadAheadEvicted       MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_read_ahead_evicted"`
	NewrelicmysqlInnodbBufferPoolReadAheadRnd           MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_read_ahead_rnd"`
	NewrelicmysqlInnodbBufferPoolReadRequests           MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_read_requests"`
	NewrelicmysqlInnodbBufferPoolReads                  MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_reads"`
	NewrelicmysqlInnodbBufferPoolTotal                  MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_total"`
	NewrelicmysqlInnodbBufferPoolUsed                   MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_used"`
	NewrelicmysqlInnodbBufferPoolUtilization            MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_utilization"`
	NewrelicmysqlInnodbBufferPoolWaitFree               MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_wait_free"`
	NewrelicmysqlInnodbBufferPoolWriteRequests          MetricConfig `mapstructure:"newrelicmysql.innodb.buffer_pool_write_requests"`
	NewrelicmysqlInnodbCheckpointAge                    MetricConfig `mapstructure:"newrelicmysql.innodb.checkpoint_age"`
	NewrelicmysqlInnodbCurrentRowLocks                  MetricConfig `mapstructure:"newrelicmysql.innodb.current_row_locks"`
	NewrelicmysqlInnodbCurrentTransactions              MetricConfig `mapstructure:"newrelicmysql.innodb.current_transactions"`
	NewrelicmysqlInnodbDataFsyncs                       MetricConfig `mapstructure:"newrelicmysql.innodb.data_fsyncs"`
	NewrelicmysqlInnodbDataPendingFsyncs                MetricConfig `mapstructure:"newrelicmysql.innodb.data_pending_fsyncs"`
	NewrelicmysqlInnodbDataPendingReads                 MetricConfig `mapstructure:"newrelicmysql.innodb.data_pending_reads"`
	NewrelicmysqlInnodbDataPendingWrites                MetricConfig `mapstructure:"newrelicmysql.innodb.data_pending_writes"`
	NewrelicmysqlInnodbDataRead                         MetricConfig `mapstructure:"newrelicmysql.innodb.data_read"`
	NewrelicmysqlInnodbDataReads                        MetricConfig `mapstructure:"newrelicmysql.innodb.data_reads"`
	NewrelicmysqlInnodbDataWrites                       MetricConfig `mapstructure:"newrelicmysql.innodb.data_writes"`
	NewrelicmysqlInnodbDataWritten                      MetricConfig `mapstructure:"newrelicmysql.innodb.data_written"`
	NewrelicmysqlInnodbDblwrPagesWritten                MetricConfig `mapstructure:"newrelicmysql.innodb.dblwr_pages_written"`
	NewrelicmysqlInnodbDblwrWrites                      MetricConfig `mapstructure:"newrelicmysql.innodb.dblwr_writes"`
	NewrelicmysqlInnodbHashIndexCellsTotal              MetricConfig `mapstructure:"newrelicmysql.innodb.hash_index_cells_total"`
	NewrelicmysqlInnodbHashIndexCellsUsed               MetricConfig `mapstructure:"newrelicmysql.innodb.hash_index_cells_used"`
	NewrelicmysqlInnodbHistoryListLength                MetricConfig `mapstructure:"newrelicmysql.innodb.history_list_length"`
	NewrelicmysqlInnodbIbufFreeList                     MetricConfig `mapstructure:"newrelicmysql.innodb.ibuf_free_list"`
	NewrelicmysqlInnodbIbufMergedDeleteMarks            MetricConfig `mapstructure:"newrelicmysql.innodb.ibuf_merged_delete_marks"`
	NewrelicmysqlInnodbIbufMergedDeletes                MetricConfig `mapstructure:"newrelicmysql.innodb.ibuf_merged_deletes"`
	NewrelicmysqlInnodbIbufMergedInserts                MetricConfig `mapstructure:"newrelicmysql.innodb.ibuf_merged_inserts"`
	NewrelicmysqlInnodbIbufMerges                       MetricConfig `mapstructure:"newrelicmysql.innodb.ibuf_merges"`
	NewrelicmysqlInnodbIbufSegmentSize                  MetricConfig `mapstructure:"newrelicmysql.innodb.ibuf_segment_size"`
	NewrelicmysqlInnodbIbufSize                         MetricConfig `mapstructure:"newrelicmysql.innodb.ibuf_size"`
	NewrelicmysqlInnodbLockStructs                      MetricConfig `mapstructure:"newrelicmysql.innodb.lock_structs"`
	NewrelicmysqlInnodbLockedTables                     MetricConfig `mapstructure:"newrelicmysql.innodb.locked_tables"`
	NewrelicmysqlInnodbLockedTransactions               MetricConfig `mapstructure:"newrelicmysql.innodb.locked_transactions"`
	NewrelicmysqlInnodbLogWaits                         MetricConfig `mapstructure:"newrelicmysql.innodb.log_waits"`
	NewrelicmysqlInnodbLogWriteRequests                 MetricConfig `mapstructure:"newrelicmysql.innodb.log_write_requests"`
	NewrelicmysqlInnodbLogWrites                        MetricConfig `mapstructure:"newrelicmysql.innodb.log_writes"`
	NewrelicmysqlInnodbLsnCurrent                       MetricConfig `mapstructure:"newrelicmysql.innodb.lsn_current"`
	NewrelicmysqlInnodbLsnFlushed                       MetricConfig `mapstructure:"newrelicmysql.innodb.lsn_flushed"`
	NewrelicmysqlInnodbLsnLastCheckpoint                MetricConfig `mapstructure:"newrelicmysql.innodb.lsn_last_checkpoint"`
	NewrelicmysqlInnodbMasterThreadActiveLoops          MetricConfig `mapstructure:"newrelicmysql.innodb.master_thread_active_loops"`
	NewrelicmysqlInnodbMasterThreadIdleLoops            MetricConfig `mapstructure:"newrelicmysql.innodb.master_thread_idle_loops"`
	NewrelicmysqlInnodbMemAdaptiveHash                  MetricConfig `mapstructure:"newrelicmysql.innodb.mem_adaptive_hash"`
	NewrelicmysqlInnodbMemAdditionalPool                MetricConfig `mapstructure:"newrelicmysql.innodb.mem_additional_pool"`
	NewrelicmysqlInnodbMemDictionary                    MetricConfig `mapstructure:"newrelicmysql.innodb.mem_dictionary"`
	NewrelicmysqlInnodbMemFileSystem                    MetricConfig `mapstructure:"newrelicmysql.innodb.mem_file_system"`
	NewrelicmysqlInnodbMemLockSystem                    MetricConfig `mapstructure:"newrelicmysql.innodb.mem_lock_system"`
	NewrelicmysqlInnodbMemPageHash                      MetricConfig `mapstructure:"newrelicmysql.innodb.mem_page_hash"`
	NewrelicmysqlInnodbMemRecoverySystem                MetricConfig `mapstructure:"newrelicmysql.innodb.mem_recovery_system"`
	NewrelicmysqlInnodbMemThreadHash                    MetricConfig `mapstructure:"newrelicmysql.innodb.mem_thread_hash"`
	NewrelicmysqlInnodbMemTotal                         MetricConfig `mapstructure:"newrelicmysql.innodb.mem_total"`
	NewrelicmysqlInnodbMutexOsWaits                     MetricConfig `mapstructure:"newrelicmysql.innodb.mutex_os_waits"`
	NewrelicmysqlInnodbMutexSpinRounds                  MetricConfig `mapstructure:"newrelicmysql.innodb.mutex_spin_rounds"`
	NewrelicmysqlInnodbMutexSpinWaits                   MetricConfig `mapstructure:"newrelicmysql.innodb.mutex_spin_waits"`
	NewrelicmysqlInnodbNumOpenFiles                     MetricConfig `mapstructure:"newrelicmysql.innodb.num_open_files"`
	NewrelicmysqlInnodbOsFileFsyncs                     MetricConfig `mapstructure:"newrelicmysql.innodb.os_file_fsyncs"`
	NewrelicmysqlInnodbOsFileReads                      MetricConfig `mapstructure:"newrelicmysql.innodb.os_file_reads"`
	NewrelicmysqlInnodbOsFileWrites                     MetricConfig `mapstructure:"newrelicmysql.innodb.os_file_writes"`
	NewrelicmysqlInnodbOsLogFsyncs                      MetricConfig `mapstructure:"newrelicmysql.innodb.os_log_fsyncs"`
	NewrelicmysqlInnodbOsLogPendingFsyncs               MetricConfig `mapstructure:"newrelicmysql.innodb.os_log_pending_fsyncs"`
	NewrelicmysqlInnodbOsLogPendingWrites               MetricConfig `mapstructure:"newrelicmysql.innodb.os_log_pending_writes"`
	NewrelicmysqlInnodbOsLogWritten                     MetricConfig `mapstructure:"newrelicmysql.innodb.os_log_written"`
	NewrelicmysqlInnodbPageSize                         MetricConfig `mapstructure:"newrelicmysql.innodb.page_size"`
	NewrelicmysqlInnodbPagesCreated                     MetricConfig `mapstructure:"newrelicmysql.innodb.pages_created"`
	NewrelicmysqlInnodbPagesRead                        MetricConfig `mapstructure:"newrelicmysql.innodb.pages_read"`
	NewrelicmysqlInnodbPagesWritten                     MetricConfig `mapstructure:"newrelicmysql.innodb.pages_written"`
	NewrelicmysqlInnodbPendingAioLogIos                 MetricConfig `mapstructure:"newrelicmysql.innodb.pending_aio_log_ios"`
	NewrelicmysqlInnodbPendingAioSyncIos                MetricConfig `mapstructure:"newrelicmysql.innodb.pending_aio_sync_ios"`
	NewrelicmysqlInnodbPendingBufferPoolFlushes         MetricConfig `mapstructure:"newrelicmysql.innodb.pending_buffer_pool_flushes"`
	NewrelicmysqlInnodbPendingCheckpointWrites          MetricConfig `mapstructure:"newrelicmysql.innodb.pending_checkpoint_writes"`
	NewrelicmysqlInnodbPendingIbufAioReads              MetricConfig `mapstructure:"newrelicmysql.innodb.pending_ibuf_aio_reads"`
	NewrelicmysqlInnodbPendingLogFlushes                MetricConfig `mapstructure:"newrelicmysql.innodb.pending_log_flushes"`
	NewrelicmysqlInnodbPendingLogWrites                 MetricConfig `mapstructure:"newrelicmysql.innodb.pending_log_writes"`
	NewrelicmysqlInnodbPendingNormalAioReads            MetricConfig `mapstructure:"newrelicmysql.innodb.pending_normal_aio_reads"`
	NewrelicmysqlInnodbPendingNormalAioWrites           MetricConfig `mapstructure:"newrelicmysql.innodb.pending_normal_aio_writes"`
	NewrelicmysqlInnodbPurgeTrxID                       MetricConfig `mapstructure:"newrelicmysql.innodb.purge_trx_id"`
	NewrelicmysqlInnodbPurgeUndoNo                      MetricConfig `mapstructure:"newrelicmysql.innodb.purge_undo_no"`
	NewrelicmysqlInnodbQueriesInside                    MetricConfig `mapstructure:"newrelicmysql.innodb.queries_inside"`
	NewrelicmysqlInnodbQueriesQueued                    MetricConfig `mapstructure:"newrelicmysql.innodb.queries_queued"`
	NewrelicmysqlInnodbReadViews                        MetricConfig `mapstructure:"newrelicmysql.innodb.read_views"`
	NewrelicmysqlInnodbRedoLogEnabled                   MetricConfig `mapstructure:"newrelicmysql.innodb.redo_log_enabled"`
	NewrelicmysqlInnodbRowLockCurrentWaits              MetricConfig `mapstructure:"newrelicmysql.innodb.row_lock_current_waits"`
	NewrelicmysqlInnodbRowLockTime                      MetricConfig `mapstructure:"newrelicmysql.innodb.row_lock_time"`
	NewrelicmysqlInnodbRowLockTimeAvg                   MetricConfig `mapstructure:"newrelicmysql.innodb.row_lock_time_avg"`
	NewrelicmysqlInnodbRowLockTimeMax                   MetricConfig `mapstructure:"newrelicmysql.innodb.row_lock_time_max"`
	NewrelicmysqlInnodbRowLockWaits                     MetricConfig `mapstructure:"newrelicmysql.innodb.row_lock_waits"`
	NewrelicmysqlInnodbRowsDeleted                      MetricConfig `mapstructure:"newrelicmysql.innodb.rows_deleted"`
	NewrelicmysqlInnodbRowsInserted                     MetricConfig `mapstructure:"newrelicmysql.innodb.rows_inserted"`
	NewrelicmysqlInnodbRowsRead                         MetricConfig `mapstructure:"newrelicmysql.innodb.rows_read"`
	NewrelicmysqlInnodbRowsUpdated                      MetricConfig `mapstructure:"newrelicmysql.innodb.rows_updated"`
	NewrelicmysqlInnodbSLockOsWaits                     MetricConfig `mapstructure:"newrelicmysql.innodb.s_lock_os_waits"`
	NewrelicmysqlInnodbSLockSpinRounds                  MetricConfig `mapstructure:"newrelicmysql.innodb.s_lock_spin_rounds"`
	NewrelicmysqlInnodbSLockSpinWaits                   MetricConfig `mapstructure:"newrelicmysql.innodb.s_lock_spin_waits"`
	NewrelicmysqlInnodbSemaphoreWaitTime                MetricConfig `mapstructure:"newrelicmysql.innodb.semaphore_wait_time"`
	NewrelicmysqlInnodbSemaphoreWaits                   MetricConfig `mapstructure:"newrelicmysql.innodb.semaphore_waits"`
	NewrelicmysqlInnodbTablesInUse                      MetricConfig `mapstructure:"newrelicmysql.innodb.tables_in_use"`
	NewrelicmysqlInnodbTruncatedStatusWrites            MetricConfig `mapstructure:"newrelicmysql.innodb.truncated_status_writes"`
	NewrelicmysqlInnodbUndoTablespacesActive            MetricConfig `mapstructure:"newrelicmysql.innodb.undo_tablespaces_active"`
	NewrelicmysqlInnodbUndoTablespacesExplicit          MetricConfig `mapstructure:"newrelicmysql.innodb.undo_tablespaces_explicit"`
	NewrelicmysqlInnodbUndoTablespacesImplicit          MetricConfig `mapstructure:"newrelicmysql.innodb.undo_tablespaces_implicit"`
	NewrelicmysqlInnodbUndoTablespacesTotal             MetricConfig `mapstructure:"newrelicmysql.innodb.undo_tablespaces_total"`
	NewrelicmysqlInnodbXLockOsWaits                     MetricConfig `mapstructure:"newrelicmysql.innodb.x_lock_os_waits"`
	NewrelicmysqlInnodbXLockSpinRounds                  MetricConfig `mapstructure:"newrelicmysql.innodb.x_lock_spin_rounds"`
	NewrelicmysqlInnodbXLockSpinWaits                   MetricConfig `mapstructure:"newrelicmysql.innodb.x_lock_spin_waits"`
	NewrelicmysqlMyisamKeyBufferBytesUnflushed          MetricConfig `mapstructure:"newrelicmysql.myisam.key_buffer_bytes_unflushed"`
	NewrelicmysqlMyisamKeyBufferBytesUsed               MetricConfig `mapstructure:"newrelicmysql.myisam.key_buffer_bytes_used"`
	NewrelicmysqlMyisamKeyBufferSize                    MetricConfig `mapstructure:"newrelicmysql.myisam.key_buffer_size"`
	NewrelicmysqlMyisamKeyReadRequests                  MetricConfig `mapstructure:"newrelicmysql.myisam.key_read_requests"`
	NewrelicmysqlMyisamKeyReads                         MetricConfig `mapstructure:"newrelicmysql.myisam.key_reads"`
	NewrelicmysqlMyisamKeyWriteRequests                 MetricConfig `mapstructure:"newrelicmysql.myisam.key_write_requests"`
	NewrelicmysqlMyisamKeyWrites                        MetricConfig `mapstructure:"newrelicmysql.myisam.key_writes"`
	NewrelicmysqlNetAbortedClients                      MetricConfig `mapstructure:"newrelicmysql.net.aborted_clients"`
	NewrelicmysqlNetAbortedConnects                     MetricConfig `mapstructure:"newrelicmysql.net.aborted_connects"`
	NewrelicmysqlNetConnections                         MetricConfig `mapstructure:"newrelicmysql.net.connections"`
	NewrelicmysqlNetMaxConnections                      MetricConfig `mapstructure:"newrelicmysql.net.max_connections"`
	NewrelicmysqlNetMaxConnectionsAvailable             MetricConfig `mapstructure:"newrelicmysql.net.max_connections_available"`
	NewrelicmysqlNetMaxUsedConnections                  MetricConfig `mapstructure:"newrelicmysql.net.max_used_connections"`
	NewrelicmysqlPerformanceBytesReceived               MetricConfig `mapstructure:"newrelicmysql.performance.bytes_received"`
	NewrelicmysqlPerformanceBytesSent                   MetricConfig `mapstructure:"newrelicmysql.performance.bytes_sent"`
	NewrelicmysqlPerformanceCreatedTmpDiskTables        MetricConfig `mapstructure:"newrelicmysql.performance.created_tmp_disk_tables"`
	NewrelicmysqlPerformanceCreatedTmpFiles             MetricConfig `mapstructure:"newrelicmysql.performance.created_tmp_files"`
	NewrelicmysqlPerformanceCreatedTmpTables            MetricConfig `mapstructure:"newrelicmysql.performance.created_tmp_tables"`
	NewrelicmysqlPerformanceHandlerCommit               MetricConfig `mapstructure:"newrelicmysql.performance.handler_commit"`
	NewrelicmysqlPerformanceHandlerDelete               MetricConfig `mapstructure:"newrelicmysql.performance.handler_delete"`
	NewrelicmysqlPerformanceHandlerPrepare              MetricConfig `mapstructure:"newrelicmysql.performance.handler_prepare"`
	NewrelicmysqlPerformanceHandlerReadFirst            MetricConfig `mapstructure:"newrelicmysql.performance.handler_read_first"`
	NewrelicmysqlPerformanceHandlerReadKey              MetricConfig `mapstructure:"newrelicmysql.performance.handler_read_key"`
	NewrelicmysqlPerformanceHandlerReadNext             MetricConfig `mapstructure:"newrelicmysql.performance.handler_read_next"`
	NewrelicmysqlPerformanceHandlerReadPrev             MetricConfig `mapstructure:"newrelicmysql.performance.handler_read_prev"`
	NewrelicmysqlPerformanceHandlerReadRnd              MetricConfig `mapstructure:"newrelicmysql.performance.handler_read_rnd"`
	NewrelicmysqlPerformanceHandlerReadRndNext          MetricConfig `mapstructure:"newrelicmysql.performance.handler_read_rnd_next"`
	NewrelicmysqlPerformanceHandlerRollback             MetricConfig `mapstructure:"newrelicmysql.performance.handler_rollback"`
	NewrelicmysqlPerformanceHandlerUpdate               MetricConfig `mapstructure:"newrelicmysql.performance.handler_update"`
	NewrelicmysqlPerformanceHandlerWrite                MetricConfig `mapstructure:"newrelicmysql.performance.handler_write"`
	NewrelicmysqlPerformanceKeyCacheUtilization         MetricConfig `mapstructure:"newrelicmysql.performance.key_cache_utilization"`
	NewrelicmysqlPerformanceMaxPreparedStmtCount        MetricConfig `mapstructure:"newrelicmysql.performance.max_prepared_stmt_count"`
	NewrelicmysqlPerformanceOpenFiles                   MetricConfig `mapstructure:"newrelicmysql.performance.open_files"`
	NewrelicmysqlPerformanceOpenTables                  MetricConfig `mapstructure:"newrelicmysql.performance.open_tables"`
	NewrelicmysqlPerformanceOpenedTables                MetricConfig `mapstructure:"newrelicmysql.performance.opened_tables"`
	NewrelicmysqlPerformancePerformanceSchemaDigestLost MetricConfig `mapstructure:"newrelicmysql.performance.performance_schema_digest_lost"`
	NewrelicmysqlPerformancePreparedStmtCount           MetricConfig `mapstructure:"newrelicmysql.performance.prepared_stmt_count"`
	NewrelicmysqlPerformanceQcacheFreeBlocks            MetricConfig `mapstructure:"newrelicmysql.performance.qcache_free_blocks"`
	NewrelicmysqlPerformanceQcacheFreeMemory            MetricConfig `mapstructure:"newrelicmysql.performance.qcache_free_memory"`
	NewrelicmysqlPerformanceQcacheHits                  MetricConfig `mapstructure:"newrelicmysql.performance.qcache_hits"`
	NewrelicmysqlPerformanceQcacheInserts               MetricConfig `mapstructure:"newrelicmysql.performance.qcache_inserts"`
	NewrelicmysqlPerformanceQcacheLowmemPrunes          MetricConfig `mapstructure:"newrelicmysql.performance.qcache_lowmem_prunes"`
	NewrelicmysqlPerformanceQcacheNotCached             MetricConfig `mapstructure:"newrelicmysql.performance.qcache_not_cached"`
	NewrelicmysqlPerformanceQcacheQueriesInCache        MetricConfig `mapstructure:"newrelicmysql.performance.qcache_queries_in_cache"`
	NewrelicmysqlPerformanceQcacheSize                  MetricConfig `mapstructure:"newrelicmysql.performance.qcache_size"`
	NewrelicmysqlPerformanceQcacheTotalBlocks           MetricConfig `mapstructure:"newrelicmysql.performance.qcache_total_blocks"`
	NewrelicmysqlPerformanceQuestions                   MetricConfig `mapstructure:"newrelicmysql.performance.questions"`
	NewrelicmysqlPerformanceSelectFullJoin              MetricConfig `mapstructure:"newrelicmysql.performance.select_full_join"`
	NewrelicmysqlPerformanceSelectFullRangeJoin         MetricConfig `mapstructure:"newrelicmysql.performance.select_full_range_join"`
	NewrelicmysqlPerformanceSelectRange                 MetricConfig `mapstructure:"newrelicmysql.performance.select_range"`
	NewrelicmysqlPerformanceSelectRangeCheck            MetricConfig `mapstructure:"newrelicmysql.performance.select_range_check"`
	NewrelicmysqlPerformanceSelectScan                  MetricConfig `mapstructure:"newrelicmysql.performance.select_scan"`
	NewrelicmysqlPerformanceSlowQueries                 MetricConfig `mapstructure:"newrelicmysql.performance.slow_queries"`
	NewrelicmysqlPerformanceSortMergePasses             MetricConfig `mapstructure:"newrelicmysql.performance.sort_merge_passes"`
	NewrelicmysqlPerformanceSortRange                   MetricConfig `mapstructure:"newrelicmysql.performance.sort_range"`
	NewrelicmysqlPerformanceSortRows                    MetricConfig `mapstructure:"newrelicmysql.performance.sort_rows"`
	NewrelicmysqlPerformanceSortScan                    MetricConfig `mapstructure:"newrelicmysql.performance.sort_scan"`
	NewrelicmysqlPerformanceTableLocksImmediate         MetricConfig `mapstructure:"newrelicmysql.performance.table_locks_immediate"`
	NewrelicmysqlPerformanceTableLocksImmediateRate     MetricConfig `mapstructure:"newrelicmysql.performance.table_locks_immediate.rate"`
	NewrelicmysqlPerformanceTableLocksWaited            MetricConfig `mapstructure:"newrelicmysql.performance.table_locks_waited"`
	NewrelicmysqlPerformanceTableOpenCache              MetricConfig `mapstructure:"newrelicmysql.performance.table_open_cache"`
	NewrelicmysqlPerformanceThreadCacheSize             MetricConfig `mapstructure:"newrelicmysql.performance.thread_cache_size"`
	NewrelicmysqlPerformanceThreadsCached               MetricConfig `mapstructure:"newrelicmysql.performance.threads_cached"`
	NewrelicmysqlPerformanceThreadsConnected            MetricConfig `mapstructure:"newrelicmysql.performance.threads_connected"`
	NewrelicmysqlPerformanceThreadsCreated              MetricConfig `mapstructure:"newrelicmysql.performance.threads_created"`
	NewrelicmysqlPerformanceThreadsRunning              MetricConfig `mapstructure:"newrelicmysql.performance.threads_running"`
	NewrelicmysqlQueryCount                             MetricConfig `mapstructure:"newrelicmysql.query.count"`
	NewrelicmysqlReplicationExecMasterLogPos            MetricConfig `mapstructure:"newrelicmysql.replication.exec_master_log_pos"`
	NewrelicmysqlReplicationLastIoErrno                 MetricConfig `mapstructure:"newrelicmysql.replication.last_io_errno"`
	NewrelicmysqlReplicationLastSQLErrno                MetricConfig `mapstructure:"newrelicmysql.replication.last_sql_errno"`
	NewrelicmysqlReplicationReadMasterLogPos            MetricConfig `mapstructure:"newrelicmysql.replication.read_master_log_pos"`
	NewrelicmysqlReplicationRelayLogSpace               MetricConfig `mapstructure:"newrelicmysql.replication.relay_log_space"`
	NewrelicmysqlReplicationSecondsBehindMaster         MetricConfig `mapstructure:"newrelicmysql.replication.seconds_behind_master"`
	NewrelicmysqlReplicationSlaveIoRunning              MetricConfig `mapstructure:"newrelicmysql.replication.slave_io_running"`
	NewrelicmysqlReplicationSlaveRunning                MetricConfig `mapstructure:"newrelicmysql.replication.slave_running"`
	NewrelicmysqlReplicationSlaveSQLRunning             MetricConfig `mapstructure:"newrelicmysql.replication.slave_sql_running"`
	NewrelicmysqlSlowqueryAvgCPUTimeMs                  MetricConfig `mapstructure:"newrelicmysql.slowquery.avg_cpu_time_ms"`
	NewrelicmysqlSlowqueryAvgElapsedTimeMs              MetricConfig `mapstructure:"newrelicmysql.slowquery.avg_elapsed_time_ms"`
	NewrelicmysqlSlowqueryAvgLockTimeMs                 MetricConfig `mapstructure:"newrelicmysql.slowquery.avg_lock_time_ms"`
	NewrelicmysqlSlowqueryAvgRowsExamined               MetricConfig `mapstructure:"newrelicmysql.slowquery.avg_rows_examined"`
	NewrelicmysqlSlowqueryAvgRowsSent                   MetricConfig `mapstructure:"newrelicmysql.slowquery.avg_rows_sent"`
	NewrelicmysqlSlowqueryExecutionCount                MetricConfig `mapstructure:"newrelicmysql.slowquery.execution_count"`
	NewrelicmysqlSlowqueryIntervalAvgElapsedTimeMs      MetricConfig `mapstructure:"newrelicmysql.slowquery.interval_avg_elapsed_time_ms"`
	NewrelicmysqlSlowqueryIntervalExecutionCount        MetricConfig `mapstructure:"newrelicmysql.slowquery.interval_execution_count"`
	NewrelicmysqlSlowqueryQueryDetails                  MetricConfig `mapstructure:"newrelicmysql.slowquery.query_details"`
	NewrelicmysqlSlowqueryQueryErrors                   MetricConfig `mapstructure:"newrelicmysql.slowquery.query_errors"`
	NewrelicmysqlUptime                                 MetricConfig `mapstructure:"newrelicmysql.uptime"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		NewrelicmysqlBinlogCacheDiskUse: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlBinlogCacheUse: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlCommands: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlConnectionCount: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlDbHandlerRollback: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlDbOpenedTables: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbActiveTransactions: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbAdaptiveHashHashSearches: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbAdaptiveHashNonHashSearches: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbAdaptiveHashPagesAdded: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbAdaptiveHashPagesRemoved: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbAvailableUndoLogs: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolBytesData: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolBytesDirty: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolDirty: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolFree: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolPagesData: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolPagesFlushed: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolPagesFree: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolPagesLruFlushed: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolPagesMadeNotYoung: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolPagesMadeYoung: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolPagesMisc: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolPagesOld: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolPagesTotal: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolReadAhead: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolReadAheadEvicted: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolReadAheadRnd: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolReadRequests: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolReads: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolTotal: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolUsed: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolUtilization: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolWaitFree: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbBufferPoolWriteRequests: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbCheckpointAge: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbCurrentRowLocks: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbCurrentTransactions: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbDataFsyncs: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbDataPendingFsyncs: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbDataPendingReads: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbDataPendingWrites: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbDataRead: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbDataReads: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbDataWrites: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbDataWritten: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbDblwrPagesWritten: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbDblwrWrites: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbHashIndexCellsTotal: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbHashIndexCellsUsed: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbHistoryListLength: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbIbufFreeList: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbIbufMergedDeleteMarks: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbIbufMergedDeletes: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbIbufMergedInserts: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbIbufMerges: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbIbufSegmentSize: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbIbufSize: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbLockStructs: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbLockedTables: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbLockedTransactions: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbLogWaits: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbLogWriteRequests: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbLogWrites: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbLsnCurrent: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbLsnFlushed: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbLsnLastCheckpoint: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbMasterThreadActiveLoops: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbMasterThreadIdleLoops: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbMemAdaptiveHash: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbMemAdditionalPool: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbMemDictionary: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbMemFileSystem: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbMemLockSystem: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbMemPageHash: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbMemRecoverySystem: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbMemThreadHash: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbMemTotal: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbMutexOsWaits: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbMutexSpinRounds: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbMutexSpinWaits: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbNumOpenFiles: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbOsFileFsyncs: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbOsFileReads: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbOsFileWrites: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbOsLogFsyncs: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbOsLogPendingFsyncs: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbOsLogPendingWrites: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbOsLogWritten: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbPageSize: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbPagesCreated: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbPagesRead: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbPagesWritten: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbPendingAioLogIos: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbPendingAioSyncIos: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbPendingBufferPoolFlushes: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbPendingCheckpointWrites: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbPendingIbufAioReads: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbPendingLogFlushes: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbPendingLogWrites: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbPendingNormalAioReads: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbPendingNormalAioWrites: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbPurgeTrxID: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbPurgeUndoNo: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbQueriesInside: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbQueriesQueued: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbReadViews: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbRedoLogEnabled: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbRowLockCurrentWaits: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbRowLockTime: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbRowLockTimeAvg: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbRowLockTimeMax: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbRowLockWaits: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbRowsDeleted: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbRowsInserted: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbRowsRead: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbRowsUpdated: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbSLockOsWaits: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbSLockSpinRounds: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbSLockSpinWaits: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbSemaphoreWaitTime: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbSemaphoreWaits: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbTablesInUse: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbTruncatedStatusWrites: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbUndoTablespacesActive: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbUndoTablespacesExplicit: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbUndoTablespacesImplicit: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbUndoTablespacesTotal: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbXLockOsWaits: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbXLockSpinRounds: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlInnodbXLockSpinWaits: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlMyisamKeyBufferBytesUnflushed: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlMyisamKeyBufferBytesUsed: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlMyisamKeyBufferSize: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlMyisamKeyReadRequests: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlMyisamKeyReads: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlMyisamKeyWriteRequests: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlMyisamKeyWrites: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlNetAbortedClients: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlNetAbortedConnects: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlNetConnections: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlNetMaxConnections: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlNetMaxConnectionsAvailable: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlNetMaxUsedConnections: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceBytesReceived: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceBytesSent: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceCreatedTmpDiskTables: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceCreatedTmpFiles: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceCreatedTmpTables: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceHandlerCommit: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceHandlerDelete: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceHandlerPrepare: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceHandlerReadFirst: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceHandlerReadKey: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceHandlerReadNext: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceHandlerReadPrev: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceHandlerReadRnd: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceHandlerReadRndNext: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceHandlerRollback: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceHandlerUpdate: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceHandlerWrite: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceKeyCacheUtilization: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceMaxPreparedStmtCount: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceOpenFiles: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceOpenTables: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceOpenedTables: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformancePerformanceSchemaDigestLost: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformancePreparedStmtCount: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceQcacheFreeBlocks: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceQcacheFreeMemory: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceQcacheHits: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceQcacheInserts: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceQcacheLowmemPrunes: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceQcacheNotCached: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceQcacheQueriesInCache: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceQcacheSize: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceQcacheTotalBlocks: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceQuestions: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceSelectFullJoin: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceSelectFullRangeJoin: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceSelectRange: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceSelectRangeCheck: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceSelectScan: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceSlowQueries: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceSortMergePasses: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceSortRange: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceSortRows: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceSortScan: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceTableLocksImmediate: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceTableLocksImmediateRate: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceTableLocksWaited: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceTableOpenCache: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceThreadCacheSize: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceThreadsCached: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceThreadsConnected: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceThreadsCreated: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlPerformanceThreadsRunning: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlQueryCount: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlReplicationExecMasterLogPos: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlReplicationLastIoErrno: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlReplicationLastSQLErrno: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlReplicationReadMasterLogPos: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlReplicationRelayLogSpace: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlReplicationSecondsBehindMaster: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlReplicationSlaveIoRunning: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlReplicationSlaveRunning: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlReplicationSlaveSQLRunning: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlSlowqueryAvgCPUTimeMs: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlSlowqueryAvgElapsedTimeMs: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlSlowqueryAvgLockTimeMs: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlSlowqueryAvgRowsExamined: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlSlowqueryAvgRowsSent: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlSlowqueryExecutionCount: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlSlowqueryIntervalAvgElapsedTimeMs: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlSlowqueryIntervalExecutionCount: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlSlowqueryQueryDetails: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlSlowqueryQueryErrors: MetricConfig{
			Enabled: true,
		},
		NewrelicmysqlUptime: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for newrelicmysql resource attributes.
type ResourceAttributesConfig struct {
	NewrelicmysqlInstanceEndpoint ResourceAttributeConfig `mapstructure:"newrelicmysql.instance.endpoint"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		NewrelicmysqlInstanceEndpoint: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for newrelicmysql metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
