// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for newrelicpostgresql resource attributes.
type ResourceAttributesConfig struct {
	DatabaseName      ResourceAttributeConfig `mapstructure:"database_name"`
	DbSystem          ResourceAttributeConfig `mapstructure:"db.system"`
	PostgresqlVersion ResourceAttributeConfig `mapstructure:"postgresql.version"`
	ServerAddress     ResourceAttributeConfig `mapstructure:"server.address"`
	ServerPort        ResourceAttributeConfig `mapstructure:"server.port"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		DatabaseName: ResourceAttributeConfig{
			Enabled: true,
		},
		DbSystem: ResourceAttributeConfig{
			Enabled: true,
		},
		PostgresqlVersion: ResourceAttributeConfig{
			Enabled: true,
		},
		ServerAddress: ResourceAttributeConfig{
			Enabled: true,
		},
		ServerPort: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}
