// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for newrelicpostgresql metrics.
type MetricsConfig struct {
	PostgresqlConnectionCount           MetricConfig `mapstructure:"postgresql.connection.count"`
	PostgresqlReplicationBackendXminAge MetricConfig `mapstructure:"postgresql.replication.backend_xmin_age"`
	PostgresqlReplicationFlushLsnDelay  MetricConfig `mapstructure:"postgresql.replication.flush_lsn_delay"`
	PostgresqlReplicationReplayLsnDelay MetricConfig `mapstructure:"postgresql.replication.replay_lsn_delay"`
	PostgresqlReplicationSentLsnDelay   MetricConfig `mapstructure:"postgresql.replication.sent_lsn_delay"`
	PostgresqlReplicationWalFlushLag    MetricConfig `mapstructure:"postgresql.replication.wal_flush_lag"`
	PostgresqlReplicationWalReplayLag   MetricConfig `mapstructure:"postgresql.replication.wal_replay_lag"`
	PostgresqlReplicationWalWriteLag    MetricConfig `mapstructure:"postgresql.replication.wal_write_lag"`
	PostgresqlReplicationWriteLsnDelay  MetricConfig `mapstructure:"postgresql.replication.write_lsn_delay"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		PostgresqlConnectionCount: MetricConfig{
			Enabled: true,
		},
		PostgresqlReplicationBackendXminAge: MetricConfig{
			Enabled: true,
		},
		PostgresqlReplicationFlushLsnDelay: MetricConfig{
			Enabled: true,
		},
		PostgresqlReplicationReplayLsnDelay: MetricConfig{
			Enabled: true,
		},
		PostgresqlReplicationSentLsnDelay: MetricConfig{
			Enabled: true,
		},
		PostgresqlReplicationWalFlushLag: MetricConfig{
			Enabled: true,
		},
		PostgresqlReplicationWalReplayLag: MetricConfig{
			Enabled: true,
		},
		PostgresqlReplicationWalWriteLag: MetricConfig{
			Enabled: true,
		},
		PostgresqlReplicationWriteLsnDelay: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for newrelicpostgresql resource attributes.
type ResourceAttributesConfig struct {
	DatabaseName      ResourceAttributeConfig `mapstructure:"database_name"`
	DbSystem          ResourceAttributeConfig `mapstructure:"db.system"`
	PostgresqlVersion ResourceAttributeConfig `mapstructure:"postgresql.version"`
	ServerAddress     ResourceAttributeConfig `mapstructure:"server.address"`
	ServerPort        ResourceAttributeConfig `mapstructure:"server.port"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		DatabaseName: ResourceAttributeConfig{
			Enabled: true,
		},
		DbSystem: ResourceAttributeConfig{
			Enabled: true,
		},
		PostgresqlVersion: ResourceAttributeConfig{
			Enabled: true,
		},
		ServerAddress: ResourceAttributeConfig{
			Enabled: true,
		},
		ServerPort: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for newrelicpostgresql metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
