// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"context"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/filter"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/plog"
	"go.opentelemetry.io/collector/receiver"
	"go.opentelemetry.io/otel/trace"
)

type eventNewrelicoracledbExecutionPlan struct {
	data   plog.LogRecordSlice // data buffer for generated log records.
	config EventConfig         // event config provided by user.
}

func (e *eventNewrelicoracledbExecutionPlan) recordEvent(ctx context.Context, timestamp pcommon.Timestamp, newrelicEventTypeAttributeValue string, queryIDAttributeValue string, planHashValueAttributeValue string, queryTextAttributeValue string, childNumberAttributeValue int64, planIDAttributeValue int64, parentIDAttributeValue int64, depthAttributeValue int64, operationAttributeValue string, optionsAttributeValue string, objectOwnerAttributeValue string, objectNameAttributeValue string, positionAttributeValue int64, costAttributeValue int64, cardinalityAttributeValue int64, bytesAttributeValue int64, cpuCostAttributeValue int64, ioCostAttributeValue int64, timestampAttributeValue string, planGeneratedTimestampAttributeValue string, tempSpaceAttributeValue int64, accessPredicatesAttributeValue string, projectionAttributeValue string, timeAttributeValue int64, filterPredicatesAttributeValue string) {
	if !e.config.Enabled {
		return
	}
	dp := e.data.AppendEmpty()
	dp.SetEventName("newrelicoracledb.execution_plan")
	dp.SetTimestamp(timestamp)

	if span := trace.SpanContextFromContext(ctx); span.IsValid() {
		dp.SetTraceID(pcommon.TraceID(span.TraceID()))
		dp.SetSpanID(pcommon.SpanID(span.SpanID()))
	}
	dp.Attributes().PutStr("newrelic.event.type", newrelicEventTypeAttributeValue)
	dp.Attributes().PutStr("query_id", queryIDAttributeValue)
	dp.Attributes().PutStr("plan_hash_value", planHashValueAttributeValue)
	dp.Attributes().PutStr("query_text", queryTextAttributeValue)
	dp.Attributes().PutInt("child_number", childNumberAttributeValue)
	dp.Attributes().PutInt("plan_id", planIDAttributeValue)
	dp.Attributes().PutInt("parent_id", parentIDAttributeValue)
	dp.Attributes().PutInt("depth", depthAttributeValue)
	dp.Attributes().PutStr("operation", operationAttributeValue)
	dp.Attributes().PutStr("options", optionsAttributeValue)
	dp.Attributes().PutStr("object_owner", objectOwnerAttributeValue)
	dp.Attributes().PutStr("object_name", objectNameAttributeValue)
	dp.Attributes().PutInt("position", positionAttributeValue)
	dp.Attributes().PutInt("cost", costAttributeValue)
	dp.Attributes().PutInt("cardinality", cardinalityAttributeValue)
	dp.Attributes().PutInt("bytes", bytesAttributeValue)
	dp.Attributes().PutInt("cpu_cost", cpuCostAttributeValue)
	dp.Attributes().PutInt("io_cost", ioCostAttributeValue)
	dp.Attributes().PutStr("timestamp", timestampAttributeValue)
	dp.Attributes().PutStr("plan_generated_timestamp", planGeneratedTimestampAttributeValue)
	dp.Attributes().PutInt("temp_space", tempSpaceAttributeValue)
	dp.Attributes().PutStr("access_predicates", accessPredicatesAttributeValue)
	dp.Attributes().PutStr("projection", projectionAttributeValue)
	dp.Attributes().PutInt("time", timeAttributeValue)
	dp.Attributes().PutStr("filter_predicates", filterPredicatesAttributeValue)

}

// emit appends recorded event data to a events slice and prepares it for recording another set of log records.
func (e *eventNewrelicoracledbExecutionPlan) emit(lrs plog.LogRecordSlice) {
	if e.config.Enabled && e.data.Len() > 0 {
		e.data.MoveAndAppendTo(lrs)
	}
}

func newEventNewrelicoracledbExecutionPlan(cfg EventConfig) eventNewrelicoracledbExecutionPlan {
	e := eventNewrelicoracledbExecutionPlan{config: cfg}
	if cfg.Enabled {
		e.data = plog.NewLogRecordSlice()
	}
	return e
}

// LogsBuilder provides an interface for scrapers to report logs while taking care of all the transformations
// required to produce log representation defined in metadata and user config.
type LogsBuilder struct {
	config                             LogsBuilderConfig // config of the logs builder.
	logsBuffer                         plog.Logs
	logRecordsBuffer                   plog.LogRecordSlice
	buildInfo                          component.BuildInfo // contains version information.
	resourceAttributeIncludeFilter     map[string]filter.Filter
	resourceAttributeExcludeFilter     map[string]filter.Filter
	eventNewrelicoracledbExecutionPlan eventNewrelicoracledbExecutionPlan
}

// LogBuilderOption applies changes to default logs builder.
type LogBuilderOption interface {
	apply(*LogsBuilder)
}

func NewLogsBuilder(lbc LogsBuilderConfig, settings receiver.Settings) *LogsBuilder {
	lb := &LogsBuilder{
		config:                             lbc,
		logsBuffer:                         plog.NewLogs(),
		logRecordsBuffer:                   plog.NewLogRecordSlice(),
		buildInfo:                          settings.BuildInfo,
		eventNewrelicoracledbExecutionPlan: newEventNewrelicoracledbExecutionPlan(lbc.Events.NewrelicoracledbExecutionPlan),
		resourceAttributeIncludeFilter:     make(map[string]filter.Filter),
		resourceAttributeExcludeFilter:     make(map[string]filter.Filter),
	}
	if lbc.ResourceAttributes.HostName.EventsInclude != nil {
		lb.resourceAttributeIncludeFilter["host.name"] = filter.CreateFilter(lbc.ResourceAttributes.HostName.EventsInclude)
	}
	if lbc.ResourceAttributes.HostName.EventsExclude != nil {
		lb.resourceAttributeExcludeFilter["host.name"] = filter.CreateFilter(lbc.ResourceAttributes.HostName.EventsExclude)
	}
	if lbc.ResourceAttributes.NewrelicoracledbInstanceName.EventsInclude != nil {
		lb.resourceAttributeIncludeFilter["newrelicoracledb.instance.name"] = filter.CreateFilter(lbc.ResourceAttributes.NewrelicoracledbInstanceName.EventsInclude)
	}
	if lbc.ResourceAttributes.NewrelicoracledbInstanceName.EventsExclude != nil {
		lb.resourceAttributeExcludeFilter["newrelicoracledb.instance.name"] = filter.CreateFilter(lbc.ResourceAttributes.NewrelicoracledbInstanceName.EventsExclude)
	}

	return lb
}

// NewResourceBuilder returns a new resource builder that should be used to build a resource associated with for the emitted logs.
func (lb *LogsBuilder) NewResourceBuilder() *ResourceBuilder {
	return NewResourceBuilder(lb.config.ResourceAttributes)
}

// ResourceLogsOption applies changes to provided resource logs.
type ResourceLogsOption interface {
	apply(plog.ResourceLogs)
}

type resourceLogsOptionFunc func(plog.ResourceLogs)

func (rlof resourceLogsOptionFunc) apply(rl plog.ResourceLogs) {
	rlof(rl)
}

// WithLogsResource sets the provided resource on the emitted ResourceLogs.
// It's recommended to use ResourceBuilder to create the resource.
func WithLogsResource(res pcommon.Resource) ResourceLogsOption {
	return resourceLogsOptionFunc(func(rl plog.ResourceLogs) {
		res.CopyTo(rl.Resource())
	})
}

// AppendLogRecord adds a log record to the logs builder.
func (lb *LogsBuilder) AppendLogRecord(lr plog.LogRecord) {
	lr.MoveTo(lb.logRecordsBuffer.AppendEmpty())
}

// EmitForResource saves all the generated logs under a new resource and updates the internal state to be ready for
// recording another set of log records as part of another resource. This function can be helpful when one scraper
// needs to emit logs from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceLogsOption arguments.
func (lb *LogsBuilder) EmitForResource(options ...ResourceLogsOption) {
	rl := plog.NewResourceLogs()
	ils := rl.ScopeLogs().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(lb.buildInfo.Version)
	lb.eventNewrelicoracledbExecutionPlan.emit(ils.LogRecords())

	for _, op := range options {
		op.apply(rl)
	}

	if lb.logRecordsBuffer.Len() > 0 {
		lb.logRecordsBuffer.MoveAndAppendTo(ils.LogRecords())
		lb.logRecordsBuffer = plog.NewLogRecordSlice()
	}

	for attr, filter := range lb.resourceAttributeIncludeFilter {
		if val, ok := rl.Resource().Attributes().Get(attr); ok && !filter.Matches(val.AsString()) {
			return
		}
	}
	for attr, filter := range lb.resourceAttributeExcludeFilter {
		if val, ok := rl.Resource().Attributes().Get(attr); ok && filter.Matches(val.AsString()) {
			return
		}
	}

	if ils.LogRecords().Len() > 0 {
		rl.MoveTo(lb.logsBuffer.ResourceLogs().AppendEmpty())
	}
}

// Emit returns all the logs accumulated by the logs builder and updates the internal state to be ready for
// recording another set of logs. This function will be responsible for applying all the transformations required to
// produce logs representation defined in metadata and user config.
func (lb *LogsBuilder) Emit(options ...ResourceLogsOption) plog.Logs {
	lb.EmitForResource(options...)
	logs := lb.logsBuffer
	lb.logsBuffer = plog.NewLogs()
	return logs
}

// RecordNewrelicoracledbExecutionPlanEvent adds a log record of newrelicoracledb.execution_plan event.
func (lb *LogsBuilder) RecordNewrelicoracledbExecutionPlanEvent(ctx context.Context, timestamp pcommon.Timestamp, newrelicEventTypeAttributeValue string, queryIDAttributeValue string, planHashValueAttributeValue string, queryTextAttributeValue string, childNumberAttributeValue int64, planIDAttributeValue int64, parentIDAttributeValue int64, depthAttributeValue int64, operationAttributeValue string, optionsAttributeValue string, objectOwnerAttributeValue string, objectNameAttributeValue string, positionAttributeValue int64, costAttributeValue int64, cardinalityAttributeValue int64, bytesAttributeValue int64, cpuCostAttributeValue int64, ioCostAttributeValue int64, timestampAttributeValue string, planGeneratedTimestampAttributeValue string, tempSpaceAttributeValue int64, accessPredicatesAttributeValue string, projectionAttributeValue string, timeAttributeValue int64, filterPredicatesAttributeValue string) {
	lb.eventNewrelicoracledbExecutionPlan.recordEvent(ctx, timestamp, newrelicEventTypeAttributeValue, queryIDAttributeValue, planHashValueAttributeValue, queryTextAttributeValue, childNumberAttributeValue, planIDAttributeValue, parentIDAttributeValue, depthAttributeValue, operationAttributeValue, optionsAttributeValue, objectOwnerAttributeValue, objectNameAttributeValue, positionAttributeValue, costAttributeValue, cardinalityAttributeValue, bytesAttributeValue, cpuCostAttributeValue, ioCostAttributeValue, timestampAttributeValue, planGeneratedTimestampAttributeValue, tempSpaceAttributeValue, accessPredicatesAttributeValue, projectionAttributeValue, timeAttributeValue, filterPredicatesAttributeValue)
}
