// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for newrelicoracledb metrics.
type MetricsConfig struct {
	NewrelicOracleDbActiveParallelSessions                                    MetricConfig `mapstructure:"newrelic.oracle.db.active_parallel_sessions"`
	NewrelicOracleDbActiveSerialSessions                                      MetricConfig `mapstructure:"newrelic.oracle.db.active_serial_sessions"`
	NewrelicOracleDbAverageActiveSessions                                     MetricConfig `mapstructure:"newrelic.oracle.db.average_active_sessions"`
	NewrelicOracleDbBackgroundCheckpointsPerSecond                            MetricConfig `mapstructure:"newrelic.oracle.db.background_checkpoints_per_second"`
	NewrelicOracleDbBackgroundCPUUsagePerSecond                               MetricConfig `mapstructure:"newrelic.oracle.db.background_cpu_usage_per_second"`
	NewrelicOracleDbBackgroundTimePerSecond                                   MetricConfig `mapstructure:"newrelic.oracle.db.background_time_per_second"`
	NewrelicOracleDbBlockChangesPerSecond                                     MetricConfig `mapstructure:"newrelic.oracle.db.block_changes_per_second"`
	NewrelicOracleDbBlockChangesPerTransaction                                MetricConfig `mapstructure:"newrelic.oracle.db.block_changes_per_transaction"`
	NewrelicOracleDbBlockChangesPerUserCall                                   MetricConfig `mapstructure:"newrelic.oracle.db.block_changes_per_user_call"`
	NewrelicOracleDbBlockGetsPerSecond                                        MetricConfig `mapstructure:"newrelic.oracle.db.block_gets_per_second"`
	NewrelicOracleDbBlockGetsPerTransaction                                   MetricConfig `mapstructure:"newrelic.oracle.db.block_gets_per_transaction"`
	NewrelicOracleDbBlockGetsPerUserCall                                      MetricConfig `mapstructure:"newrelic.oracle.db.block_gets_per_user_call"`
	NewrelicOracleDbBranchNodeSplitsPerSecond                                 MetricConfig `mapstructure:"newrelic.oracle.db.branch_node_splits_per_second"`
	NewrelicOracleDbBranchNodeSplitsPerTransaction                            MetricConfig `mapstructure:"newrelic.oracle.db.branch_node_splits_per_transaction"`
	NewrelicOracleDbCapturedUserCalls                                         MetricConfig `mapstructure:"newrelic.oracle.db.captured_user_calls"`
	NewrelicOracleDbConsistentReadChangesPerSecond                            MetricConfig `mapstructure:"newrelic.oracle.db.consistent_read_changes_per_second"`
	NewrelicOracleDbConsistentReadChangesPerTransaction                       MetricConfig `mapstructure:"newrelic.oracle.db.consistent_read_changes_per_transaction"`
	NewrelicOracleDbConsistentReadGetsPerSecond                               MetricConfig `mapstructure:"newrelic.oracle.db.consistent_read_gets_per_second"`
	NewrelicOracleDbConsistentReadGetsPerTransaction                          MetricConfig `mapstructure:"newrelic.oracle.db.consistent_read_gets_per_transaction"`
	NewrelicOracleDbCPUTimeRatio                                              MetricConfig `mapstructure:"newrelic.oracle.db.cpu_time_ratio"`
	NewrelicOracleDbCPUUsagePerSecond                                         MetricConfig `mapstructure:"newrelic.oracle.db.cpu_usage_per_second"`
	NewrelicOracleDbCPUUsagePerTransaction                                    MetricConfig `mapstructure:"newrelic.oracle.db.cpu_usage_per_transaction"`
	NewrelicOracleDbCrBlocksCreatedPerSecond                                  MetricConfig `mapstructure:"newrelic.oracle.db.cr_blocks_created_per_second"`
	NewrelicOracleDbCrBlocksCreatedPerTransaction                             MetricConfig `mapstructure:"newrelic.oracle.db.cr_blocks_created_per_transaction"`
	NewrelicOracleDbCrUndoRecordsAppliedPerSecond                             MetricConfig `mapstructure:"newrelic.oracle.db.cr_undo_records_applied_per_second"`
	NewrelicOracleDbCrUndoRecordsAppliedPerTransaction                        MetricConfig `mapstructure:"newrelic.oracle.db.cr_undo_records_applied_per_transaction"`
	NewrelicOracleDbCurrentLogons                                             MetricConfig `mapstructure:"newrelic.oracle.db.current_logons"`
	NewrelicOracleDbCurrentOpenCursors                                        MetricConfig `mapstructure:"newrelic.oracle.db.current_open_cursors"`
	NewrelicOracleDbCursorCacheHitRatio                                       MetricConfig `mapstructure:"newrelic.oracle.db.cursor_cache_hit_ratio"`
	NewrelicOracleDbCursorCacheHitsPerAttempts                                MetricConfig `mapstructure:"newrelic.oracle.db.cursor_cache_hits_per_attempts"`
	NewrelicOracleDbDatabaseCPUTimePerSecond                                  MetricConfig `mapstructure:"newrelic.oracle.db.database_cpu_time_per_second"`
	NewrelicOracleDbDbwrCheckpointsPerSecond                                  MetricConfig `mapstructure:"newrelic.oracle.db.dbwr_checkpoints_per_second"`
	NewrelicOracleDbEnqueueDeadlocksPerSecond                                 MetricConfig `mapstructure:"newrelic.oracle.db.enqueue_deadlocks_per_second"`
	NewrelicOracleDbEnqueueDeadlocksPerTransaction                            MetricConfig `mapstructure:"newrelic.oracle.db.enqueue_deadlocks_per_transaction"`
	NewrelicOracleDbEnqueueRequestsPerSecond                                  MetricConfig `mapstructure:"newrelic.oracle.db.enqueue_requests_per_second"`
	NewrelicOracleDbEnqueueRequestsPerTransaction                             MetricConfig `mapstructure:"newrelic.oracle.db.enqueue_requests_per_transaction"`
	NewrelicOracleDbEnqueueTimeoutsPerSecond                                  MetricConfig `mapstructure:"newrelic.oracle.db.enqueue_timeouts_per_second"`
	NewrelicOracleDbEnqueueTimeoutsPerTransaction                             MetricConfig `mapstructure:"newrelic.oracle.db.enqueue_timeouts_per_transaction"`
	NewrelicOracleDbEnqueueWaitsPerSecond                                     MetricConfig `mapstructure:"newrelic.oracle.db.enqueue_waits_per_second"`
	NewrelicOracleDbEnqueueWaitsPerTransaction                                MetricConfig `mapstructure:"newrelic.oracle.db.enqueue_waits_per_transaction"`
	NewrelicOracleDbExecuteWithoutParseRatio                                  MetricConfig `mapstructure:"newrelic.oracle.db.execute_without_parse_ratio"`
	NewrelicOracleDbExecutionsPerSecond                                       MetricConfig `mapstructure:"newrelic.oracle.db.executions_per_second"`
	NewrelicOracleDbExecutionsPerTransaction                                  MetricConfig `mapstructure:"newrelic.oracle.db.executions_per_transaction"`
	NewrelicOracleDbExecutionsPerUserCall                                     MetricConfig `mapstructure:"newrelic.oracle.db.executions_per_user_call"`
	NewrelicOracleDbFullIndexScansPerSecond                                   MetricConfig `mapstructure:"newrelic.oracle.db.full_index_scans_per_second"`
	NewrelicOracleDbFullIndexScansPerTransaction                              MetricConfig `mapstructure:"newrelic.oracle.db.full_index_scans_per_transaction"`
	NewrelicOracleDbGcCrBlockReceivedPerSecond                                MetricConfig `mapstructure:"newrelic.oracle.db.gc_cr_block_received_per_second"`
	NewrelicOracleDbGcCrBlockReceivedPerTransaction                           MetricConfig `mapstructure:"newrelic.oracle.db.gc_cr_block_received_per_transaction"`
	NewrelicOracleDbGcCrBlockRecievedPerSecond                                MetricConfig `mapstructure:"newrelic.oracle.db.gc_cr_block_recieved_per_second"`
	NewrelicOracleDbGcCrBlockRecievedPerTransaction                           MetricConfig `mapstructure:"newrelic.oracle.db.gc_cr_block_recieved_per_transaction"`
	NewrelicOracleDbGcCurrentBlockReceivedPerSecond                           MetricConfig `mapstructure:"newrelic.oracle.db.gc_current_block_received_per_second"`
	NewrelicOracleDbGcCurrentBlockReceivedPerTransaction                      MetricConfig `mapstructure:"newrelic.oracle.db.gc_current_block_received_per_transaction"`
	NewrelicOracleDbGlobalCacheAverageCrGetTime                               MetricConfig `mapstructure:"newrelic.oracle.db.global_cache_average_cr_get_time"`
	NewrelicOracleDbGlobalCacheAverageCrGetTimePerSecond                      MetricConfig `mapstructure:"newrelic.oracle.db.global_cache_average_cr_get_time_per_second"`
	NewrelicOracleDbGlobalCacheAverageCurrentGetTime                          MetricConfig `mapstructure:"newrelic.oracle.db.global_cache_average_current_get_time"`
	NewrelicOracleDbGlobalCacheAverageCurrentGetTimePerSecond                 MetricConfig `mapstructure:"newrelic.oracle.db.global_cache_average_current_get_time_per_second"`
	NewrelicOracleDbHardParseCountPerSecond                                   MetricConfig `mapstructure:"newrelic.oracle.db.hard_parse_count_per_second"`
	NewrelicOracleDbHardParseCountPerTransaction                              MetricConfig `mapstructure:"newrelic.oracle.db.hard_parse_count_per_transaction"`
	NewrelicOracleDbHostCPUUsagePerSecond                                     MetricConfig `mapstructure:"newrelic.oracle.db.host_cpu_usage_per_second"`
	NewrelicOracleDbHostCPUUtilization                                        MetricConfig `mapstructure:"newrelic.oracle.db.host_cpu_utilization"`
	NewrelicOracleDbLeafNodeSplitsPerSecond                                   MetricConfig `mapstructure:"newrelic.oracle.db.leaf_node_splits_per_second"`
	NewrelicOracleDbLeafNodeSplitsPerTransaction                              MetricConfig `mapstructure:"newrelic.oracle.db.leaf_node_splits_per_transaction"`
	NewrelicOracleDbLibraryCacheHitRatio                                      MetricConfig `mapstructure:"newrelic.oracle.db.library_cache_hit_ratio"`
	NewrelicOracleDbLibraryCacheMissRatio                                     MetricConfig `mapstructure:"newrelic.oracle.db.library_cache_miss_ratio"`
	NewrelicOracleDbLogicalReadsPerSecond                                     MetricConfig `mapstructure:"newrelic.oracle.db.logical_reads_per_second"`
	NewrelicOracleDbLogicalReadsPerTransaction                                MetricConfig `mapstructure:"newrelic.oracle.db.logical_reads_per_transaction"`
	NewrelicOracleDbLogonsPerSecond                                           MetricConfig `mapstructure:"newrelic.oracle.db.logons_per_second"`
	NewrelicOracleDbLogonsPerTransaction                                      MetricConfig `mapstructure:"newrelic.oracle.db.logons_per_transaction"`
	NewrelicOracleDbLongTableScansPerSecond                                   MetricConfig `mapstructure:"newrelic.oracle.db.long_table_scans_per_second"`
	NewrelicOracleDbLongTableScansPerTransaction                              MetricConfig `mapstructure:"newrelic.oracle.db.long_table_scans_per_transaction"`
	NewrelicOracleDbOpenCursorsPerSecond                                      MetricConfig `mapstructure:"newrelic.oracle.db.open_cursors_per_second"`
	NewrelicOracleDbOpenCursorsPerTransaction                                 MetricConfig `mapstructure:"newrelic.oracle.db.open_cursors_per_transaction"`
	NewrelicOracleDbOsLoad                                                    MetricConfig `mapstructure:"newrelic.oracle.db.os_load"`
	NewrelicOracleDbParseFailureCountPerSecond                                MetricConfig `mapstructure:"newrelic.oracle.db.parse_failure_count_per_second"`
	NewrelicOracleDbParseFailureCountPerTransaction                           MetricConfig `mapstructure:"newrelic.oracle.db.parse_failure_count_per_transaction"`
	NewrelicOracleDbPgaCacheHitPercentage                                     MetricConfig `mapstructure:"newrelic.oracle.db.pga_cache_hit_percentage"`
	NewrelicOracleDbPhysicalReadBytesPerSecond                                MetricConfig `mapstructure:"newrelic.oracle.db.physical_read_bytes_per_second"`
	NewrelicOracleDbPhysicalReadIoRequestsPerSecond                           MetricConfig `mapstructure:"newrelic.oracle.db.physical_read_io_requests_per_second"`
	NewrelicOracleDbPhysicalReadsPerSecond                                    MetricConfig `mapstructure:"newrelic.oracle.db.physical_reads_per_second"`
	NewrelicOracleDbPhysicalWriteBytesPerSecond                               MetricConfig `mapstructure:"newrelic.oracle.db.physical_write_bytes_per_second"`
	NewrelicOracleDbPhysicalWritesPerSecond                                   MetricConfig `mapstructure:"newrelic.oracle.db.physical_writes_per_second"`
	NewrelicOracleDbProcessLimitPercentage                                    MetricConfig `mapstructure:"newrelic.oracle.db.process_limit_percentage"`
	NewrelicOracleDbRecursiveCallsPerSecond                                   MetricConfig `mapstructure:"newrelic.oracle.db.recursive_calls_per_second"`
	NewrelicOracleDbRecursiveCallsPerTransaction                              MetricConfig `mapstructure:"newrelic.oracle.db.recursive_calls_per_transaction"`
	NewrelicOracleDbRedoWritesPerSecond                                       MetricConfig `mapstructure:"newrelic.oracle.db.redo_writes_per_second"`
	NewrelicOracleDbRedoWritesPerTransaction                                  MetricConfig `mapstructure:"newrelic.oracle.db.redo_writes_per_transaction"`
	NewrelicOracleDbResponseTimePerTransaction                                MetricConfig `mapstructure:"newrelic.oracle.db.response_time_per_transaction"`
	NewrelicOracleDbRowCacheHitRatio                                          MetricConfig `mapstructure:"newrelic.oracle.db.row_cache_hit_ratio"`
	NewrelicOracleDbRowCacheMissRatio                                         MetricConfig `mapstructure:"newrelic.oracle.db.row_cache_miss_ratio"`
	NewrelicOracleDbRowsPerSort                                               MetricConfig `mapstructure:"newrelic.oracle.db.rows_per_sort"`
	NewrelicOracleDbSessionCount                                              MetricConfig `mapstructure:"newrelic.oracle.db.session_count"`
	NewrelicOracleDbSessionLimitPercentage                                    MetricConfig `mapstructure:"newrelic.oracle.db.session_limit_percentage"`
	NewrelicOracleDbSharedPoolFreePercentage                                  MetricConfig `mapstructure:"newrelic.oracle.db.shared_pool_free_percentage"`
	NewrelicOracleDbSoftParseRatio                                            MetricConfig `mapstructure:"newrelic.oracle.db.soft_parse_ratio"`
	NewrelicOracleDbSortsPerUserCall                                          MetricConfig `mapstructure:"newrelic.oracle.db.sorts_per_user_call"`
	NewrelicOracleDbSQLServiceResponseTime                                    MetricConfig `mapstructure:"newrelic.oracle.db.sql_service_response_time"`
	NewrelicOracleDbStreamsPoolUsagePercentage                                MetricConfig `mapstructure:"newrelic.oracle.db.streams_pool_usage_percentage"`
	NewrelicOracleDbTableScansPerUserCall                                     MetricConfig `mapstructure:"newrelic.oracle.db.table_scans_per_user_call"`
	NewrelicOracleDbTotalIndexScansPerSecond                                  MetricConfig `mapstructure:"newrelic.oracle.db.total_index_scans_per_second"`
	NewrelicOracleDbTotalIndexScansPerTransaction                             MetricConfig `mapstructure:"newrelic.oracle.db.total_index_scans_per_transaction"`
	NewrelicOracleDbTotalParseCountPerSecond                                  MetricConfig `mapstructure:"newrelic.oracle.db.total_parse_count_per_second"`
	NewrelicOracleDbTotalParseCountPerTransaction                             MetricConfig `mapstructure:"newrelic.oracle.db.total_parse_count_per_transaction"`
	NewrelicOracleDbTotalTableScansPerSecond                                  MetricConfig `mapstructure:"newrelic.oracle.db.total_table_scans_per_second"`
	NewrelicOracleDbTotalTableScansPerTransaction                             MetricConfig `mapstructure:"newrelic.oracle.db.total_table_scans_per_transaction"`
	NewrelicOracleDbTransactionsPerLogon                                      MetricConfig `mapstructure:"newrelic.oracle.db.transactions_per_logon"`
	NewrelicOracleDbUserCallsPerSecond                                        MetricConfig `mapstructure:"newrelic.oracle.db.user_calls_per_second"`
	NewrelicOracleDbUserCallsPerTransaction                                   MetricConfig `mapstructure:"newrelic.oracle.db.user_calls_per_transaction"`
	NewrelicOracleDbUserCallsRatio                                            MetricConfig `mapstructure:"newrelic.oracle.db.user_calls_ratio"`
	NewrelicOracleDbUserCommitsPerSecond                                      MetricConfig `mapstructure:"newrelic.oracle.db.user_commits_per_second"`
	NewrelicOracleDbUserCommitsPercentage                                     MetricConfig `mapstructure:"newrelic.oracle.db.user_commits_percentage"`
	NewrelicOracleDbUserLimitPercentage                                       MetricConfig `mapstructure:"newrelic.oracle.db.user_limit_percentage"`
	NewrelicOracleDbUserRollbackUndoRecordsAppliedPerSecond                   MetricConfig `mapstructure:"newrelic.oracle.db.user_rollback_undo_records_applied_per_second"`
	NewrelicOracleDbUserRollbackUndoRecordsAppliedPerTransaction              MetricConfig `mapstructure:"newrelic.oracle.db.user_rollback_undo_records_applied_per_transaction"`
	NewrelicOracleDbUserRollbacksPerSecond                                    MetricConfig `mapstructure:"newrelic.oracle.db.user_rollbacks_per_second"`
	NewrelicOracleDbUserRollbacksPercentage                                   MetricConfig `mapstructure:"newrelic.oracle.db.user_rollbacks_percentage"`
	NewrelicOracleDbWaitTimeRatio                                             MetricConfig `mapstructure:"newrelic.oracle.db.wait_time_ratio"`
	NewrelicOracleDiskBlocksRead                                              MetricConfig `mapstructure:"newrelic.oracle.disk.blocks_read"`
	NewrelicOracleDiskBlocksWritten                                           MetricConfig `mapstructure:"newrelic.oracle.disk.blocks_written"`
	NewrelicOracleDiskLogicalReadsPerUserCall                                 MetricConfig `mapstructure:"newrelic.oracle.disk.logical_reads_per_user_call"`
	NewrelicOracleDiskPhysicalLobsReadsPerSecond                              MetricConfig `mapstructure:"newrelic.oracle.disk.physical_lobs_reads_per_second"`
	NewrelicOracleDiskPhysicalLobsWritesPerSecond                             MetricConfig `mapstructure:"newrelic.oracle.disk.physical_lobs_writes_per_second"`
	NewrelicOracleDiskPhysicalReadBytesPerSecond                              MetricConfig `mapstructure:"newrelic.oracle.disk.physical_read_bytes_per_second"`
	NewrelicOracleDiskPhysicalReadIoRequestsPerSecond                         MetricConfig `mapstructure:"newrelic.oracle.disk.physical_read_io_requests_per_second"`
	NewrelicOracleDiskPhysicalReadsPerSecond                                  MetricConfig `mapstructure:"newrelic.oracle.disk.physical_reads_per_second"`
	NewrelicOracleDiskPhysicalWriteBytesPerSecond                             MetricConfig `mapstructure:"newrelic.oracle.disk.physical_write_bytes_per_second"`
	NewrelicOracleDiskPhysicalWriteIoRequestsPerSecond                        MetricConfig `mapstructure:"newrelic.oracle.disk.physical_write_io_requests_per_second"`
	NewrelicOracleDiskPhysicalWriteTotalIoRequestsPerSecond                   MetricConfig `mapstructure:"newrelic.oracle.disk.physical_write_total_io_requests_per_second"`
	NewrelicOracleDiskPhysicalWritesPerSecond                                 MetricConfig `mapstructure:"newrelic.oracle.disk.physical_writes_per_second"`
	NewrelicOracleDiskReadTimeInMiliseconds                                   MetricConfig `mapstructure:"newrelic.oracle.disk.read_time_in_miliseconds"`
	NewrelicOracleDiskReadTimeInMilliseconds                                  MetricConfig `mapstructure:"newrelic.oracle.disk.read_time_in_milliseconds"`
	NewrelicOracleDiskReadTimeMilliseconds                                    MetricConfig `mapstructure:"newrelic.oracle.disk.read_time_milliseconds"`
	NewrelicOracleDiskReads                                                   MetricConfig `mapstructure:"newrelic.oracle.disk.reads"`
	NewrelicOracleDiskSortPerSecond                                           MetricConfig `mapstructure:"newrelic.oracle.disk.sort_per_second"`
	NewrelicOracleDiskSortPerTransaction                                      MetricConfig `mapstructure:"newrelic.oracle.disk.sort_per_transaction"`
	NewrelicOracleDiskTempSpaceUsedBytes                                      MetricConfig `mapstructure:"newrelic.oracle.disk.temp_space_used_bytes"`
	NewrelicOracleDiskTempSpaceUsedInBytes                                    MetricConfig `mapstructure:"newrelic.oracle.disk.temp_space_used_in_bytes"`
	NewrelicOracleDiskWriteTimeInMiliseconds                                  MetricConfig `mapstructure:"newrelic.oracle.disk.write_time_in_miliseconds"`
	NewrelicOracleDiskWriteTimeInMilliseconds                                 MetricConfig `mapstructure:"newrelic.oracle.disk.write_time_in_milliseconds"`
	NewrelicOracleDiskWriteTimeMilliseconds                                   MetricConfig `mapstructure:"newrelic.oracle.disk.write_time_milliseconds"`
	NewrelicOracleDiskWrites                                                  MetricConfig `mapstructure:"newrelic.oracle.disk.writes"`
	NewrelicOracleInstanceCdbDatafilesOffline                                 MetricConfig `mapstructure:"newrelic.oracle.instance.cdb_datafiles_offline"`
	NewrelicOracleLockedAccounts                                              MetricConfig `mapstructure:"newrelic.oracle.locked_accounts"`
	NewrelicOracleLongRunningQueries                                          MetricConfig `mapstructure:"newrelic.oracle.long_running_queries"`
	NewrelicOracleMemoryBufferCacheHitRatio                                   MetricConfig `mapstructure:"newrelic.oracle.memory.buffer_cache_hit_ratio"`
	NewrelicOracleMemoryGlobalCacheBlocksCorrupted                            MetricConfig `mapstructure:"newrelic.oracle.memory.global_cache_blocks_corrupted"`
	NewrelicOracleMemoryGlobalCacheBlocksLost                                 MetricConfig `mapstructure:"newrelic.oracle.memory.global_cache_blocks_lost"`
	NewrelicOracleMemoryPgaAllocatedBytes                                     MetricConfig `mapstructure:"newrelic.oracle.memory.pga_allocated_bytes"`
	NewrelicOracleMemoryPgaAllocatedInBytes                                   MetricConfig `mapstructure:"newrelic.oracle.memory.pga_allocated_in_bytes"`
	NewrelicOracleMemoryPgaFreeableBytes                                      MetricConfig `mapstructure:"newrelic.oracle.memory.pga_freeable_bytes"`
	NewrelicOracleMemoryPgaFreeableInBytes                                    MetricConfig `mapstructure:"newrelic.oracle.memory.pga_freeable_in_bytes"`
	NewrelicOracleMemoryPgaInUseBytes                                         MetricConfig `mapstructure:"newrelic.oracle.memory.pga_in_use_bytes"`
	NewrelicOracleMemoryPgaInUseInBytes                                       MetricConfig `mapstructure:"newrelic.oracle.memory.pga_in_use_in_bytes"`
	NewrelicOracleMemoryPgaMaxSizeBytes                                       MetricConfig `mapstructure:"newrelic.oracle.memory.pga_max_size_bytes"`
	NewrelicOracleMemoryPgaMaxSizeInBytes                                     MetricConfig `mapstructure:"newrelic.oracle.memory.pga_max_size_in_bytes"`
	NewrelicOracleMemoryRedoAllocationHitRatio                                MetricConfig `mapstructure:"newrelic.oracle.memory.redo_allocation_hit_ratio"`
	NewrelicOracleMemoryRedoGeneratedBytesPerSecond                           MetricConfig `mapstructure:"newrelic.oracle.memory.redo_generated_bytes_per_second"`
	NewrelicOracleMemoryRedoGeneratedBytesPerTransaction                      MetricConfig `mapstructure:"newrelic.oracle.memory.redo_generated_bytes_per_transaction"`
	NewrelicOracleMemorySortsRatio                                            MetricConfig `mapstructure:"newrelic.oracle.memory.sorts_ratio"`
	NewrelicOracleNetworkIoMegabytesPerSecond                                 MetricConfig `mapstructure:"newrelic.oracle.network.io_megabytes_per_second"`
	NewrelicOracleNetworkIoRequestsPerSecond                                  MetricConfig `mapstructure:"newrelic.oracle.network.io_requests_per_second"`
	NewrelicOracleNetworkTrafficBytePerSecond                                 MetricConfig `mapstructure:"newrelic.oracle.network.traffic_byte_per_second"`
	NewrelicOracleNetworkTrafficBytesPerSecond                                MetricConfig `mapstructure:"newrelic.oracle.network.traffic_bytes_per_second"`
	NewrelicOracleQueryPhysicalLobsReadsPerTransaction                        MetricConfig `mapstructure:"newrelic.oracle.query.physical_lobs_reads_per_transaction"`
	NewrelicOracleQueryPhysicalLobsWritesPerTransaction                       MetricConfig `mapstructure:"newrelic.oracle.query.physical_lobs_writes_per_transaction"`
	NewrelicOracleQueryPhysicalReadsPerTransaction                            MetricConfig `mapstructure:"newrelic.oracle.query.physical_reads_per_transaction"`
	NewrelicOracleQueryPhysicalWritesPerTransaction                           MetricConfig `mapstructure:"newrelic.oracle.query.physical_writes_per_transaction"`
	NewrelicOracleQuerySQLServiceResponseTime                                 MetricConfig `mapstructure:"newrelic.oracle.query.sql_service_response_time"`
	NewrelicOracleQueryTransactionsPerSecond                                  MetricConfig `mapstructure:"newrelic.oracle.query.transactions_per_second"`
	NewrelicOracleRedoLogFileSwitch                                           MetricConfig `mapstructure:"newrelic.oracle.redo_log.file_switch"`
	NewrelicOracleRedoLogFileSwitchArchivingNeeded                            MetricConfig `mapstructure:"newrelic.oracle.redo_log.file_switch_archiving_needed"`
	NewrelicOracleRedoLogFileSwitchCheckpointIncomplete                       MetricConfig `mapstructure:"newrelic.oracle.redo_log.file_switch_checkpoint_incomplete"`
	NewrelicOracleRedoLogLogFileSwitch                                        MetricConfig `mapstructure:"newrelic.oracle.redo_log.log_file_switch"`
	NewrelicOracleRedoLogLogFileSwitchArchivingNeeded                         MetricConfig `mapstructure:"newrelic.oracle.redo_log.log_file_switch_archiving_needed"`
	NewrelicOracleRedoLogLogFileSwitchCheckpointIncomplete                    MetricConfig `mapstructure:"newrelic.oracle.redo_log.log_file_switch_checkpoint_incomplete"`
	NewrelicOracleRedoLogWaits                                                MetricConfig `mapstructure:"newrelic.oracle.redo_log.waits"`
	NewrelicOracleRollbackSegmentsGets                                        MetricConfig `mapstructure:"newrelic.oracle.rollback_segments.gets"`
	NewrelicOracleRollbackSegmentsRatioWait                                   MetricConfig `mapstructure:"newrelic.oracle.rollback_segments.ratio_wait"`
	NewrelicOracleRollbackSegmentsWaits                                       MetricConfig `mapstructure:"newrelic.oracle.rollback_segments.waits"`
	NewrelicOracleSgaBufferBusyWaits                                          MetricConfig `mapstructure:"newrelic.oracle.sga.buffer_busy_waits"`
	NewrelicOracleSgaFixedSizeBytes                                           MetricConfig `mapstructure:"newrelic.oracle.sga.fixed_size_bytes"`
	NewrelicOracleSgaFixedSizeInBytes                                         MetricConfig `mapstructure:"newrelic.oracle.sga.fixed_size_in_bytes"`
	NewrelicOracleSgaFreeBufferInspected                                      MetricConfig `mapstructure:"newrelic.oracle.sga.free_buffer_inspected"`
	NewrelicOracleSgaFreeBufferWaits                                          MetricConfig `mapstructure:"newrelic.oracle.sga.free_buffer_waits"`
	NewrelicOracleSgaHitRatio                                                 MetricConfig `mapstructure:"newrelic.oracle.sga.hit_ratio"`
	NewrelicOracleSgaLogBufferAllocationRetriesRatio                          MetricConfig `mapstructure:"newrelic.oracle.sga.log_buffer_allocation_retries_ratio"`
	NewrelicOracleSgaLogBufferRedoAllocationRetries                           MetricConfig `mapstructure:"newrelic.oracle.sga.log_buffer_redo_allocation_retries"`
	NewrelicOracleSgaLogBufferRedoEntries                                     MetricConfig `mapstructure:"newrelic.oracle.sga.log_buffer_redo_entries"`
	NewrelicOracleSgaLogBufferSpaceWaits                                      MetricConfig `mapstructure:"newrelic.oracle.sga.log_buffer_space_waits"`
	NewrelicOracleSgaRedoBuffersBytes                                         MetricConfig `mapstructure:"newrelic.oracle.sga.redo_buffers_bytes"`
	NewrelicOracleSgaRedoBuffersInBytes                                       MetricConfig `mapstructure:"newrelic.oracle.sga.redo_buffers_in_bytes"`
	NewrelicOracleSgaSharedPoolDictCacheMissRatio                             MetricConfig `mapstructure:"newrelic.oracle.sga.shared_pool_dict_cache_miss_ratio"`
	NewrelicOracleSgaSharedPoolLibraryCacheHitRatio                           MetricConfig `mapstructure:"newrelic.oracle.sga.shared_pool_library_cache_hit_ratio"`
	NewrelicOracleSgaSharedPoolLibraryCacheReloadRatio                        MetricConfig `mapstructure:"newrelic.oracle.sga.shared_pool_library_cache_reload_ratio"`
	NewrelicOracleSgaSharedPoolLibraryCacheShareableMemoryPerStatementBytes   MetricConfig `mapstructure:"newrelic.oracle.sga.shared_pool_library_cache_shareable_memory_per_statement_bytes"`
	NewrelicOracleSgaSharedPoolLibraryCacheShareableMemoryPerStatementInBytes MetricConfig `mapstructure:"newrelic.oracle.sga.shared_pool_library_cache_shareable_memory_per_statement_in_bytes"`
	NewrelicOracleSgaSharedPoolLibraryCacheShareableMemoryPerUserBytes        MetricConfig `mapstructure:"newrelic.oracle.sga.shared_pool_library_cache_shareable_memory_per_user_bytes"`
	NewrelicOracleSgaSharedPoolLibraryCacheShareableMemoryPerUserInBytes      MetricConfig `mapstructure:"newrelic.oracle.sga.shared_pool_library_cache_shareable_memory_per_user_in_bytes"`
	NewrelicOracleSgaUgaTotalMemoryBytes                                      MetricConfig `mapstructure:"newrelic.oracle.sga.uga_total_memory_bytes"`
	NewrelicOracleSgaUgaTotalMemoryInBytes                                    MetricConfig `mapstructure:"newrelic.oracle.sga.uga_total_memory_in_bytes"`
	NewrelicOracleSortsDiskBytes                                              MetricConfig `mapstructure:"newrelic.oracle.sorts.disk_bytes"`
	NewrelicOracleSortsDiskInBytes                                            MetricConfig `mapstructure:"newrelic.oracle.sorts.disk_in_bytes"`
	NewrelicOracleSortsMemoryBytes                                            MetricConfig `mapstructure:"newrelic.oracle.sorts.memory_bytes"`
	NewrelicOracleSortsMemoryInBytes                                          MetricConfig `mapstructure:"newrelic.oracle.sorts.memory_in_bytes"`
	NewrelicOracleTablespaceIsOffline                                         MetricConfig `mapstructure:"newrelic.oracle.tablespace.is_offline"`
	NewrelicOracleTablespaceOfflineCdbDatafiles                               MetricConfig `mapstructure:"newrelic.oracle.tablespace.offline_cdb_datafiles"`
	NewrelicOracleTablespaceOfflinePdbDatafiles                               MetricConfig `mapstructure:"newrelic.oracle.tablespace.offline_pdb_datafiles"`
	NewrelicOracleTablespacePdbDatafilesNonWrite                              MetricConfig `mapstructure:"newrelic.oracle.tablespace.pdb_datafiles_non_write"`
	NewrelicOracleTablespaceSpaceConsumedBytes                                MetricConfig `mapstructure:"newrelic.oracle.tablespace.space_consumed_bytes"`
	NewrelicOracleTablespaceSpaceConsumedInBytes                              MetricConfig `mapstructure:"newrelic.oracle.tablespace.space_consumed_in_bytes"`
	NewrelicOracleTablespaceSpaceReservedBytes                                MetricConfig `mapstructure:"newrelic.oracle.tablespace.space_reserved_bytes"`
	NewrelicOracleTablespaceSpaceReservedInBytes                              MetricConfig `mapstructure:"newrelic.oracle.tablespace.space_reserved_in_bytes"`
	NewrelicOracleTablespaceSpaceUsedPercentage                               MetricConfig `mapstructure:"newrelic.oracle.tablespace.space_used_percentage"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		NewrelicOracleDbActiveParallelSessions: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbActiveSerialSessions: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbAverageActiveSessions: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbBackgroundCheckpointsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbBackgroundCPUUsagePerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbBackgroundTimePerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbBlockChangesPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbBlockChangesPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbBlockChangesPerUserCall: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbBlockGetsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbBlockGetsPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbBlockGetsPerUserCall: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbBranchNodeSplitsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbBranchNodeSplitsPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbCapturedUserCalls: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbConsistentReadChangesPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbConsistentReadChangesPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbConsistentReadGetsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbConsistentReadGetsPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbCPUTimeRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbCPUUsagePerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbCPUUsagePerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbCrBlocksCreatedPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbCrBlocksCreatedPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbCrUndoRecordsAppliedPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbCrUndoRecordsAppliedPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbCurrentLogons: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbCurrentOpenCursors: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbCursorCacheHitRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbCursorCacheHitsPerAttempts: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbDatabaseCPUTimePerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbDbwrCheckpointsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbEnqueueDeadlocksPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbEnqueueDeadlocksPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbEnqueueRequestsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbEnqueueRequestsPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbEnqueueTimeoutsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbEnqueueTimeoutsPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbEnqueueWaitsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbEnqueueWaitsPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbExecuteWithoutParseRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbExecutionsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbExecutionsPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbExecutionsPerUserCall: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbFullIndexScansPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbFullIndexScansPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbGcCrBlockReceivedPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbGcCrBlockReceivedPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbGcCrBlockRecievedPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbGcCrBlockRecievedPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbGcCurrentBlockReceivedPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbGcCurrentBlockReceivedPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbGlobalCacheAverageCrGetTime: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbGlobalCacheAverageCrGetTimePerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbGlobalCacheAverageCurrentGetTime: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbGlobalCacheAverageCurrentGetTimePerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbHardParseCountPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbHardParseCountPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbHostCPUUsagePerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbHostCPUUtilization: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbLeafNodeSplitsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbLeafNodeSplitsPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbLibraryCacheHitRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbLibraryCacheMissRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbLogicalReadsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbLogicalReadsPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbLogonsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbLogonsPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbLongTableScansPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbLongTableScansPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbOpenCursorsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbOpenCursorsPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbOsLoad: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbParseFailureCountPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbParseFailureCountPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbPgaCacheHitPercentage: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbPhysicalReadBytesPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbPhysicalReadIoRequestsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbPhysicalReadsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbPhysicalWriteBytesPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbPhysicalWritesPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbProcessLimitPercentage: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbRecursiveCallsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbRecursiveCallsPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbRedoWritesPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbRedoWritesPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbResponseTimePerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbRowCacheHitRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbRowCacheMissRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbRowsPerSort: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbSessionCount: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbSessionLimitPercentage: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbSharedPoolFreePercentage: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbSoftParseRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbSortsPerUserCall: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbSQLServiceResponseTime: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbStreamsPoolUsagePercentage: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbTableScansPerUserCall: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbTotalIndexScansPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbTotalIndexScansPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbTotalParseCountPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbTotalParseCountPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbTotalTableScansPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbTotalTableScansPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbTransactionsPerLogon: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbUserCallsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbUserCallsPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbUserCallsRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbUserCommitsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbUserCommitsPercentage: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbUserLimitPercentage: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbUserRollbackUndoRecordsAppliedPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbUserRollbackUndoRecordsAppliedPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbUserRollbacksPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbUserRollbacksPercentage: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDbWaitTimeRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskBlocksRead: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskBlocksWritten: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskLogicalReadsPerUserCall: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskPhysicalLobsReadsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskPhysicalLobsWritesPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskPhysicalReadBytesPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskPhysicalReadIoRequestsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskPhysicalReadsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskPhysicalWriteBytesPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskPhysicalWriteIoRequestsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskPhysicalWriteTotalIoRequestsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskPhysicalWritesPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskReadTimeInMiliseconds: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskReadTimeInMilliseconds: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskReadTimeMilliseconds: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskReads: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskSortPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskSortPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskTempSpaceUsedBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskTempSpaceUsedInBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskWriteTimeInMiliseconds: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskWriteTimeInMilliseconds: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskWriteTimeMilliseconds: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleDiskWrites: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleInstanceCdbDatafilesOffline: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleLockedAccounts: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleLongRunningQueries: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleMemoryBufferCacheHitRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleMemoryGlobalCacheBlocksCorrupted: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleMemoryGlobalCacheBlocksLost: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleMemoryPgaAllocatedBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleMemoryPgaAllocatedInBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleMemoryPgaFreeableBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleMemoryPgaFreeableInBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleMemoryPgaInUseBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleMemoryPgaInUseInBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleMemoryPgaMaxSizeBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleMemoryPgaMaxSizeInBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleMemoryRedoAllocationHitRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleMemoryRedoGeneratedBytesPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleMemoryRedoGeneratedBytesPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleMemorySortsRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleNetworkIoMegabytesPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleNetworkIoRequestsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleNetworkTrafficBytePerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleNetworkTrafficBytesPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleQueryPhysicalLobsReadsPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleQueryPhysicalLobsWritesPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleQueryPhysicalReadsPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleQueryPhysicalWritesPerTransaction: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleQuerySQLServiceResponseTime: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleQueryTransactionsPerSecond: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleRedoLogFileSwitch: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleRedoLogFileSwitchArchivingNeeded: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleRedoLogFileSwitchCheckpointIncomplete: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleRedoLogLogFileSwitch: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleRedoLogLogFileSwitchArchivingNeeded: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleRedoLogLogFileSwitchCheckpointIncomplete: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleRedoLogWaits: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleRollbackSegmentsGets: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleRollbackSegmentsRatioWait: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleRollbackSegmentsWaits: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaBufferBusyWaits: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaFixedSizeBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaFixedSizeInBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaFreeBufferInspected: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaFreeBufferWaits: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaHitRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaLogBufferAllocationRetriesRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaLogBufferRedoAllocationRetries: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaLogBufferRedoEntries: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaLogBufferSpaceWaits: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaRedoBuffersBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaRedoBuffersInBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaSharedPoolDictCacheMissRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaSharedPoolLibraryCacheHitRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaSharedPoolLibraryCacheReloadRatio: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaSharedPoolLibraryCacheShareableMemoryPerStatementBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaSharedPoolLibraryCacheShareableMemoryPerStatementInBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaSharedPoolLibraryCacheShareableMemoryPerUserBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaSharedPoolLibraryCacheShareableMemoryPerUserInBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaUgaTotalMemoryBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSgaUgaTotalMemoryInBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSortsDiskBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSortsDiskInBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSortsMemoryBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleSortsMemoryInBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleTablespaceIsOffline: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleTablespaceOfflineCdbDatafiles: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleTablespaceOfflinePdbDatafiles: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleTablespacePdbDatafilesNonWrite: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleTablespaceSpaceConsumedBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleTablespaceSpaceConsumedInBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleTablespaceSpaceReservedBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleTablespaceSpaceReservedInBytes: MetricConfig{
			Enabled: true,
		},
		NewrelicOracleTablespaceSpaceUsedPercentage: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for newrelicoracledb resource attributes.
type ResourceAttributesConfig struct {
	HostName                   ResourceAttributeConfig `mapstructure:"host.name"`
	NewrelicOracleDbID         ResourceAttributeConfig `mapstructure:"newrelic.oracle.db.id"`
	NewrelicOracleGlobalName   ResourceAttributeConfig `mapstructure:"newrelic.oracle.global.name"`
	NewrelicOracleInstanceID   ResourceAttributeConfig `mapstructure:"newrelic.oracle.instance.id"`
	NewrelicOracleInstanceName ResourceAttributeConfig `mapstructure:"newrelic.oracle.instance.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		HostName: ResourceAttributeConfig{
			Enabled: true,
		},
		NewrelicOracleDbID: ResourceAttributeConfig{
			Enabled: true,
		},
		NewrelicOracleGlobalName: ResourceAttributeConfig{
			Enabled: true,
		},
		NewrelicOracleInstanceID: ResourceAttributeConfig{
			Enabled: true,
		},
		NewrelicOracleInstanceName: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for newrelicoracledb metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
