// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"context"
	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/plog"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.opentelemetry.io/otel/trace"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
	"testing"
	"time"
)

type eventsTestDataSet int

const (
	eventTestDataSetDefault eventsTestDataSet = iota
	eventTestDataSetAll
	eventTestDataSetNone
)

func TestLogsBuilderAppendLogRecord(t *testing.T) {
	observedZapCore, _ := observer.New(zap.WarnLevel)
	settings := receivertest.NewNopSettings(receivertest.NopType)
	settings.Logger = zap.New(observedZapCore)
	lb := NewLogsBuilder(loadLogsBuilderConfig(t, "all_set"), settings)

	rb := lb.NewResourceBuilder()
	rb.SetHostName("host.name-val")
	rb.SetNewrelicoracledbInstanceName("newrelicoracledb.instance.name-val")
	res := rb.Emit()

	// append the first log record
	lr := plog.NewLogRecord()
	lr.SetTimestamp(pcommon.NewTimestampFromTime(time.Now()))
	lr.Attributes().PutStr("type", "log")
	lr.Body().SetStr("the first log record")

	// append the second log record
	lr2 := plog.NewLogRecord()
	lr2.SetTimestamp(pcommon.NewTimestampFromTime(time.Now()))
	lr2.Attributes().PutStr("type", "event")
	lr2.Body().SetStr("the second log record")

	lb.AppendLogRecord(lr)
	lb.AppendLogRecord(lr2)

	logs := lb.Emit(WithLogsResource(res))
	assert.Equal(t, 1, logs.ResourceLogs().Len())

	rl := logs.ResourceLogs().At(0)
	assert.Equal(t, 1, rl.ScopeLogs().Len())

	sl := rl.ScopeLogs().At(0)
	assert.Equal(t, ScopeName, sl.Scope().Name())
	assert.Equal(t, lb.buildInfo.Version, sl.Scope().Version())

	assert.Equal(t, 2, sl.LogRecords().Len())

	attrVal, ok := sl.LogRecords().At(0).Attributes().Get("type")
	assert.True(t, ok)
	assert.Equal(t, "log", attrVal.Str())

	assert.Equal(t, pcommon.ValueTypeStr, sl.LogRecords().At(0).Body().Type())
	assert.Equal(t, "the first log record", sl.LogRecords().At(0).Body().Str())

	attrVal, ok = sl.LogRecords().At(1).Attributes().Get("type")
	assert.True(t, ok)
	assert.Equal(t, "event", attrVal.Str())

	assert.Equal(t, pcommon.ValueTypeStr, sl.LogRecords().At(1).Body().Type())
	assert.Equal(t, "the second log record", sl.LogRecords().At(1).Body().Str())
}
func TestLogsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		eventsSet   eventsTestDataSet
		resAttrsSet eventsTestDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			eventsSet:   eventTestDataSetAll,
			resAttrsSet: eventTestDataSetAll,
		},
		{
			name:        "none_set",
			eventsSet:   eventTestDataSetNone,
			resAttrsSet: eventTestDataSetNone,
			expectEmpty: true,
		},
		{
			name:        "filter_set_include",
			resAttrsSet: eventTestDataSetAll,
		},
		{
			name:        "filter_set_exclude",
			resAttrsSet: eventTestDataSetAll,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			timestamp := pcommon.Timestamp(1_000_001_000)
			traceID := [16]byte{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}
			spanID := [8]byte{0, 1, 2, 3, 4, 5, 6, 7}
			ctx := trace.ContextWithSpanContext(context.Background(), trace.NewSpanContext(trace.SpanContextConfig{
				TraceID:    trace.TraceID(traceID),
				SpanID:     trace.SpanID(spanID),
				TraceFlags: trace.FlagsSampled,
			}))
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			lb := NewLogsBuilder(loadLogsBuilderConfig(t, tt.name), settings)

			expectedWarnings := 0

			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultEventsCount := 0
			allEventsCount := 0
			defaultEventsCount++
			allEventsCount++
			lb.RecordNewrelicoracledbExecutionPlanEvent(ctx, timestamp, "newrelic.event.type-val", "query_id-val", "plan_hash_value-val", "query_text-val", 12, 7, 9, 5, "operation-val", "options-val", "object_owner-val", "object_name-val", 8, 4, 11, 5, 8, 7, "timestamp-val", "plan_generated_timestamp-val", 10, "access_predicates-val", "projection-val", 4, "filter_predicates-val")

			rb := lb.NewResourceBuilder()
			rb.SetHostName("host.name-val")
			rb.SetNewrelicoracledbInstanceName("newrelicoracledb.instance.name-val")
			res := rb.Emit()
			logs := lb.Emit(WithLogsResource(res))

			if tt.expectEmpty || ((tt.name == "default" || tt.name == "filter_set_include") && defaultEventsCount == 0) {
				assert.Equal(t, 0, logs.ResourceLogs().Len())
				return
			}

			assert.Equal(t, 1, logs.ResourceLogs().Len())
			rl := logs.ResourceLogs().At(0)
			assert.Equal(t, res, rl.Resource())
			assert.Equal(t, 1, rl.ScopeLogs().Len())
			lrs := rl.ScopeLogs().At(0).LogRecords()
			if tt.eventsSet == eventTestDataSetDefault {
				assert.Equal(t, defaultEventsCount, lrs.Len())
			}
			if tt.eventsSet == eventTestDataSetAll {
				assert.Equal(t, allEventsCount, lrs.Len())
			}
			validatedEvents := make(map[string]bool)
			for i := 0; i < lrs.Len(); i++ {
				switch lrs.At(i).EventName() {
				case "newrelicoracledb.execution_plan":
					assert.False(t, validatedEvents["newrelicoracledb.execution_plan"], "Found a duplicate in the events slice: newrelicoracledb.execution_plan")
					validatedEvents["newrelicoracledb.execution_plan"] = true
					lr := lrs.At(i)
					assert.Equal(t, timestamp, lr.Timestamp())
					assert.Equal(t, pcommon.TraceID(traceID), lr.TraceID())
					assert.Equal(t, pcommon.SpanID(spanID), lr.SpanID())
					attrVal, ok := lr.Attributes().Get("newrelic.event.type")
					assert.True(t, ok)
					assert.Equal(t, "newrelic.event.type-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("query_id")
					assert.True(t, ok)
					assert.Equal(t, "query_id-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("plan_hash_value")
					assert.True(t, ok)
					assert.Equal(t, "plan_hash_value-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("query_text")
					assert.True(t, ok)
					assert.Equal(t, "query_text-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("child_number")
					assert.True(t, ok)
					assert.EqualValues(t, 12, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("plan_id")
					assert.True(t, ok)
					assert.EqualValues(t, 7, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("parent_id")
					assert.True(t, ok)
					assert.EqualValues(t, 9, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("depth")
					assert.True(t, ok)
					assert.EqualValues(t, 5, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("operation")
					assert.True(t, ok)
					assert.Equal(t, "operation-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("options")
					assert.True(t, ok)
					assert.Equal(t, "options-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("object_owner")
					assert.True(t, ok)
					assert.Equal(t, "object_owner-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("object_name")
					assert.True(t, ok)
					assert.Equal(t, "object_name-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("position")
					assert.True(t, ok)
					assert.EqualValues(t, 8, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("cost")
					assert.True(t, ok)
					assert.EqualValues(t, 4, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("cardinality")
					assert.True(t, ok)
					assert.EqualValues(t, 11, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("bytes")
					assert.True(t, ok)
					assert.EqualValues(t, 5, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("cpu_cost")
					assert.True(t, ok)
					assert.EqualValues(t, 8, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("io_cost")
					assert.True(t, ok)
					assert.EqualValues(t, 7, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("timestamp")
					assert.True(t, ok)
					assert.Equal(t, "timestamp-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("plan_generated_timestamp")
					assert.True(t, ok)
					assert.Equal(t, "plan_generated_timestamp-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("temp_space")
					assert.True(t, ok)
					assert.EqualValues(t, 10, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("access_predicates")
					assert.True(t, ok)
					assert.Equal(t, "access_predicates-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("projection")
					assert.True(t, ok)
					assert.Equal(t, "projection-val", attrVal.Str())
					attrVal, ok = lr.Attributes().Get("time")
					assert.True(t, ok)
					assert.EqualValues(t, 4, attrVal.Int())
					attrVal, ok = lr.Attributes().Get("filter_predicates")
					assert.True(t, ok)
					assert.Equal(t, "filter_predicates-val", attrVal.Str())
				}
			}
		})
	}
}
