// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for newrelicsqlserver metrics.
type MetricsConfig struct {
	SqlserverAccessPageSplitsPerSec                           MetricConfig `mapstructure:"sqlserver.access.page_splits_per_sec"`
	SqlserverActivequeryWaitTimeSeconds                       MetricConfig `mapstructure:"sqlserver.activequery.wait_time_seconds"`
	SqlserverBlockingQueryDetails                             MetricConfig `mapstructure:"sqlserver.blocking_query.details"`
	SqlserverBufferCacheHitRatio                              MetricConfig `mapstructure:"sqlserver.buffer.cache_hit_ratio"`
	SqlserverBufferCheckpointPagesPerSec                      MetricConfig `mapstructure:"sqlserver.buffer.checkpoint_pages_per_sec"`
	SqlserverBufferPageLifeExpectancy                         MetricConfig `mapstructure:"sqlserver.buffer.page_life_expectancy"`
	SqlserverBufferpoolBatchRequestsPerSec                    MetricConfig `mapstructure:"sqlserver.bufferpool.batch_requests_per_sec"`
	SqlserverBufferpoolPageLifeExpectancyMs                   MetricConfig `mapstructure:"sqlserver.bufferpool.page_life_expectancy_ms"`
	SqlserverConnectionsUser                                  MetricConfig `mapstructure:"sqlserver.connections.user"`
	SqlserverDatabaseBufferpoolSizePerDatabaseBytes           MetricConfig `mapstructure:"sqlserver.database.bufferpool.size_per_database_bytes"`
	SqlserverDatabaseIoStallMs                                MetricConfig `mapstructure:"sqlserver.database.io.stall_ms"`
	SqlserverDatabaseLogBytesFlushedPerSec                    MetricConfig `mapstructure:"sqlserver.database.log.bytes_flushed_per_sec"`
	SqlserverDatabaseLogFlushWaitsPerSec                      MetricConfig `mapstructure:"sqlserver.database.log.flush_waits_per_sec"`
	SqlserverDatabaseLogFlushesPerSec                         MetricConfig `mapstructure:"sqlserver.database.log.flushes_per_sec"`
	SqlserverDatabaseLogTransactionGrowth                     MetricConfig `mapstructure:"sqlserver.database.log.transaction_growth"`
	SqlserverDatabaseLogUsedSpaceMb                           MetricConfig `mapstructure:"sqlserver.database.log.used_space_mb"`
	SqlserverDatabaseMaxDiskSizeBytes                         MetricConfig `mapstructure:"sqlserver.database.max_disk_size_bytes"`
	SqlserverDatabasePageFileAvailableBytes                   MetricConfig `mapstructure:"sqlserver.database.page_file_available_bytes"`
	SqlserverDatabasePageFileTotalBytes                       MetricConfig `mapstructure:"sqlserver.database.page_file_total_bytes"`
	SqlserverDatabasePrincipalsApplicationRoles               MetricConfig `mapstructure:"sqlserver.database.principals.applicationRoles"`
	SqlserverDatabasePrincipalsOld                            MetricConfig `mapstructure:"sqlserver.database.principals.old"`
	SqlserverDatabasePrincipalsOrphanedUsers                  MetricConfig `mapstructure:"sqlserver.database.principals.orphanedUsers"`
	SqlserverDatabasePrincipalsRecentlyCreated                MetricConfig `mapstructure:"sqlserver.database.principals.recentlyCreated"`
	SqlserverDatabasePrincipalsRoles                          MetricConfig `mapstructure:"sqlserver.database.principals.roles"`
	SqlserverDatabasePrincipalsSQLUsers                       MetricConfig `mapstructure:"sqlserver.database.principals.sqlUsers"`
	SqlserverDatabasePrincipalsTotal                          MetricConfig `mapstructure:"sqlserver.database.principals.total"`
	SqlserverDatabasePrincipalsUsers                          MetricConfig `mapstructure:"sqlserver.database.principals.users"`
	SqlserverDatabasePrincipalsWindowsUsers                   MetricConfig `mapstructure:"sqlserver.database.principals.windowsUsers"`
	SqlserverDatabaseRoleMembersApplicationRoles              MetricConfig `mapstructure:"sqlserver.database.role.members.applicationRoles"`
	SqlserverDatabaseRoleMembersCrossRole                     MetricConfig `mapstructure:"sqlserver.database.role.members.crossRole"`
	SqlserverDatabaseRoleMembersHighPrivilege                 MetricConfig `mapstructure:"sqlserver.database.role.members.highPrivilege"`
	SqlserverDatabaseRoleMembersUnique                        MetricConfig `mapstructure:"sqlserver.database.role.members.unique"`
	SqlserverDatabaseRoleMembershipsActive                    MetricConfig `mapstructure:"sqlserver.database.role.memberships.active"`
	SqlserverDatabaseRoleMembershipsCustom                    MetricConfig `mapstructure:"sqlserver.database.role.memberships.custom"`
	SqlserverDatabaseRoleMembershipsNested                    MetricConfig `mapstructure:"sqlserver.database.role.memberships.nested"`
	SqlserverDatabaseRoleMembershipsTotal                     MetricConfig `mapstructure:"sqlserver.database.role.memberships.total"`
	SqlserverDatabaseRoleMembershipsUsers                     MetricConfig `mapstructure:"sqlserver.database.role.memberships.users"`
	SqlserverDatabaseRolePermissionMemberCount                MetricConfig `mapstructure:"sqlserver.database.role.permission.memberCount"`
	SqlserverDatabaseRolePermissionRiskLevel                  MetricConfig `mapstructure:"sqlserver.database.role.permission.riskLevel"`
	SqlserverDatabaseRoleRolesEmpty                           MetricConfig `mapstructure:"sqlserver.database.role.roles.empty"`
	SqlserverDatabaseRoleRolesWithMembers                     MetricConfig `mapstructure:"sqlserver.database.role.roles.withMembers"`
	SqlserverDatabaseSizeDataMb                               MetricConfig `mapstructure:"sqlserver.database.size.data_mb"`
	SqlserverDatabaseSizeTotalMb                              MetricConfig `mapstructure:"sqlserver.database.size.total_mb"`
	SqlserverDatabaseTransactionsActive                       MetricConfig `mapstructure:"sqlserver.database.transactions.active"`
	SqlserverExecutionPlan                                    MetricConfig `mapstructure:"sqlserver.execution.plan"`
	SqlserverFailoverClusterAgClusterType                     MetricConfig `mapstructure:"sqlserver.failover_cluster.ag_cluster_type"`
	SqlserverFailoverClusterAgFailureConditionLevel           MetricConfig `mapstructure:"sqlserver.failover_cluster.ag_failure_condition_level"`
	SqlserverFailoverClusterAgHealthCheckTimeout              MetricConfig `mapstructure:"sqlserver.failover_cluster.ag_health_check_timeout"`
	SqlserverFailoverClusterAgReplicaRole                     MetricConfig `mapstructure:"sqlserver.failover_cluster.ag_replica_role"`
	SqlserverFailoverClusterAgRequiredSyncSecondaries         MetricConfig `mapstructure:"sqlserver.failover_cluster.ag_required_sync_secondaries"`
	SqlserverFailoverClusterAgSynchronizationHealth           MetricConfig `mapstructure:"sqlserver.failover_cluster.ag_synchronization_health"`
	SqlserverFailoverClusterFlowControlTimeMs                 MetricConfig `mapstructure:"sqlserver.failover_cluster.flow_control_time_ms"`
	SqlserverFailoverClusterLogBytesReceivedPerSec            MetricConfig `mapstructure:"sqlserver.failover_cluster.log_bytes_received_per_sec"`
	SqlserverFailoverClusterLogSendQueueKb                    MetricConfig `mapstructure:"sqlserver.failover_cluster.log_send_queue_kb"`
	SqlserverFailoverClusterRedoQueueKb                       MetricConfig `mapstructure:"sqlserver.failover_cluster.redo_queue_kb"`
	SqlserverFailoverClusterRedoRateKbSec                     MetricConfig `mapstructure:"sqlserver.failover_cluster.redo_rate_kb_sec"`
	SqlserverFailoverClusterTransactionDelayMs                MetricConfig `mapstructure:"sqlserver.failover_cluster.transaction_delay_ms"`
	SqlserverInstanceBackgroundProcessesCount                 MetricConfig `mapstructure:"sqlserver.instance.background_processes_count"`
	SqlserverInstanceBlockedProcessesCount                    MetricConfig `mapstructure:"sqlserver.instance.blocked_processes_count"`
	SqlserverInstanceBufferPoolHitPercent                     MetricConfig `mapstructure:"sqlserver.instance.buffer_pool_hit_percent"`
	SqlserverInstanceBufferPoolSize                           MetricConfig `mapstructure:"sqlserver.instance.buffer_pool_size"`
	SqlserverInstanceCompilationsPerBatch                     MetricConfig `mapstructure:"sqlserver.instance.compilations_per_batch"`
	SqlserverInstanceConnectionsActive                        MetricConfig `mapstructure:"sqlserver.instance.connections_active"`
	SqlserverInstanceDiskInBytes                              MetricConfig `mapstructure:"sqlserver.instance.disk_in_bytes"`
	SqlserverInstanceDormantProcessesCount                    MetricConfig `mapstructure:"sqlserver.instance.dormant_processes_count"`
	SqlserverInstanceForcedParameterizationsPerSec            MetricConfig `mapstructure:"sqlserver.instance.forced_parameterizations_per_sec"`
	SqlserverInstanceFullScansRate                            MetricConfig `mapstructure:"sqlserver.instance.full_scans_rate"`
	SqlserverInstanceLockTimeoutsRate                         MetricConfig `mapstructure:"sqlserver.instance.lock_timeouts_rate"`
	SqlserverInstanceMemoryAvailable                          MetricConfig `mapstructure:"sqlserver.instance.memory_available"`
	SqlserverInstanceMemoryTotal                              MetricConfig `mapstructure:"sqlserver.instance.memory_total"`
	SqlserverInstanceMemoryUtilizationPercent                 MetricConfig `mapstructure:"sqlserver.instance.memory_utilization_percent"`
	SqlserverInstancePageSplitsPerBatch                       MetricConfig `mapstructure:"sqlserver.instance.page_splits_per_batch"`
	SqlserverInstancePreconnectProcessesCount                 MetricConfig `mapstructure:"sqlserver.instance.preconnect_processes_count"`
	SqlserverInstanceRunnableProcessesCount                   MetricConfig `mapstructure:"sqlserver.instance.runnable_processes_count"`
	SqlserverInstanceRunnableTasks                            MetricConfig `mapstructure:"sqlserver.instance.runnable_tasks"`
	SqlserverInstanceRunningProcessesCount                    MetricConfig `mapstructure:"sqlserver.instance.running_processes_count"`
	SqlserverInstanceSleepingProcessesCount                   MetricConfig `mapstructure:"sqlserver.instance.sleeping_processes_count"`
	SqlserverInstanceSuspendedProcessesCount                  MetricConfig `mapstructure:"sqlserver.instance.suspended_processes_count"`
	SqlserverInstanceTargetMemoryKb                           MetricConfig `mapstructure:"sqlserver.instance.target_memory_kb"`
	SqlserverInstanceTransactionsPerSec                       MetricConfig `mapstructure:"sqlserver.instance.transactions_per_sec"`
	SqlserverLockModeBulkUpdate                               MetricConfig `mapstructure:"sqlserver.lock.mode.bulk_update"`
	SqlserverLockModeExclusive                                MetricConfig `mapstructure:"sqlserver.lock.mode.exclusive"`
	SqlserverLockModeIntent                                   MetricConfig `mapstructure:"sqlserver.lock.mode.intent"`
	SqlserverLockModeSchema                                   MetricConfig `mapstructure:"sqlserver.lock.mode.schema"`
	SqlserverLockModeShared                                   MetricConfig `mapstructure:"sqlserver.lock.mode.shared"`
	SqlserverLockModeSharedIntentExclusive                    MetricConfig `mapstructure:"sqlserver.lock.mode.shared_intent_exclusive"`
	SqlserverLockModeTotal                                    MetricConfig `mapstructure:"sqlserver.lock.mode.total"`
	SqlserverLockModeUpdate                                   MetricConfig `mapstructure:"sqlserver.lock.mode.update"`
	SqlserverLockResourceAllocationUnit                       MetricConfig `mapstructure:"sqlserver.lock.resource.allocation_unit"`
	SqlserverLockResourceApplication                          MetricConfig `mapstructure:"sqlserver.lock.resource.application"`
	SqlserverLockResourceDatabaseLevel                        MetricConfig `mapstructure:"sqlserver.lock.resource.database_level"`
	SqlserverLockResourceExtent                               MetricConfig `mapstructure:"sqlserver.lock.resource.extent"`
	SqlserverLockResourceFile                                 MetricConfig `mapstructure:"sqlserver.lock.resource.file"`
	SqlserverLockResourceHobt                                 MetricConfig `mapstructure:"sqlserver.lock.resource.hobt"`
	SqlserverLockResourceKey                                  MetricConfig `mapstructure:"sqlserver.lock.resource.key"`
	SqlserverLockResourceMetadata                             MetricConfig `mapstructure:"sqlserver.lock.resource.metadata"`
	SqlserverLockResourcePage                                 MetricConfig `mapstructure:"sqlserver.lock.resource.page"`
	SqlserverLockResourceRow                                  MetricConfig `mapstructure:"sqlserver.lock.resource.row"`
	SqlserverLockResourceTable                                MetricConfig `mapstructure:"sqlserver.lock.resource.table"`
	SqlserverLockResourceTotal                                MetricConfig `mapstructure:"sqlserver.lock.resource.total"`
	SqlserverLockedObject                                     MetricConfig `mapstructure:"sqlserver.locked_object"`
	SqlserverMemoryTarget                                     MetricConfig `mapstructure:"sqlserver.memory.target"`
	SqlserverMemoryTotal                                      MetricConfig `mapstructure:"sqlserver.memory.total"`
	SqlserverPlanAvgElapsedTimeMs                             MetricConfig `mapstructure:"sqlserver.plan.avg_elapsed_time_ms"`
	SqlserverSecurityServerPrincipalsCount                    MetricConfig `mapstructure:"sqlserver.security.server_principals_count"`
	SqlserverSecurityServerRoleMembersCount                   MetricConfig `mapstructure:"sqlserver.security.server_role_members_count"`
	SqlserverSlowqueryAvgElapsedTimeMs                        MetricConfig `mapstructure:"sqlserver.slowquery.avg_elapsed_time_ms"`
	SqlserverSlowqueryHistoricalAvgElapsedTimeMs              MetricConfig `mapstructure:"sqlserver.slowquery.historical_avg_elapsed_time_ms"`
	SqlserverSlowqueryHistoricalExecutionCount                MetricConfig `mapstructure:"sqlserver.slowquery.historical_execution_count"`
	SqlserverSlowqueryHistoricalLogicalReads                  MetricConfig `mapstructure:"sqlserver.slowquery.historical_logical_reads"`
	SqlserverSlowqueryHistoricalPhysicalReads                 MetricConfig `mapstructure:"sqlserver.slowquery.historical_physical_reads"`
	SqlserverSlowqueryHistoricalRows                          MetricConfig `mapstructure:"sqlserver.slowquery.historical_rows"`
	SqlserverSlowqueryHistoricalWaitTimeMs                    MetricConfig `mapstructure:"sqlserver.slowquery.historical_wait_time_ms"`
	SqlserverSlowqueryHistoricalWorkerTimeMs                  MetricConfig `mapstructure:"sqlserver.slowquery.historical_worker_time_ms"`
	SqlserverSlowqueryIntervalAvgElapsedTimeMs                MetricConfig `mapstructure:"sqlserver.slowquery.interval_avg_elapsed_time_ms"`
	SqlserverSlowqueryIntervalAvgLogicalReads                 MetricConfig `mapstructure:"sqlserver.slowquery.interval_avg_logical_reads"`
	SqlserverSlowqueryIntervalAvgPhysicalReads                MetricConfig `mapstructure:"sqlserver.slowquery.interval_avg_physical_reads"`
	SqlserverSlowqueryIntervalAvgRows                         MetricConfig `mapstructure:"sqlserver.slowquery.interval_avg_rows"`
	SqlserverSlowqueryIntervalAvgWaitTimeMs                   MetricConfig `mapstructure:"sqlserver.slowquery.interval_avg_wait_time_ms"`
	SqlserverSlowqueryIntervalAvgWorkerTimeMs                 MetricConfig `mapstructure:"sqlserver.slowquery.interval_avg_worker_time_ms"`
	SqlserverSlowqueryIntervalElapsedTimeMs                   MetricConfig `mapstructure:"sqlserver.slowquery.interval_elapsed_time_ms"`
	SqlserverSlowqueryIntervalExecutionCount                  MetricConfig `mapstructure:"sqlserver.slowquery.interval_execution_count"`
	SqlserverSlowqueryIntervalLogicalReads                    MetricConfig `mapstructure:"sqlserver.slowquery.interval_logical_reads"`
	SqlserverSlowqueryIntervalPhysicalReads                   MetricConfig `mapstructure:"sqlserver.slowquery.interval_physical_reads"`
	SqlserverSlowqueryIntervalRows                            MetricConfig `mapstructure:"sqlserver.slowquery.interval_rows"`
	SqlserverSlowqueryIntervalWaitTimeMs                      MetricConfig `mapstructure:"sqlserver.slowquery.interval_wait_time_ms"`
	SqlserverSlowqueryIntervalWorkerTimeMs                    MetricConfig `mapstructure:"sqlserver.slowquery.interval_worker_time_ms"`
	SqlserverSlowqueryQueryDetails                            MetricConfig `mapstructure:"sqlserver.slowquery.query_details"`
	SqlserverStatsConnections                                 MetricConfig `mapstructure:"sqlserver.stats.connections"`
	SqlserverStatsDeadlocksPerSec                             MetricConfig `mapstructure:"sqlserver.stats.deadlocks_per_sec"`
	SqlserverStatsKillConnectionErrorsPerSec                  MetricConfig `mapstructure:"sqlserver.stats.kill_connection_errors_per_sec"`
	SqlserverStatsLockWaitsPerSec                             MetricConfig `mapstructure:"sqlserver.stats.lock_waits_per_sec"`
	SqlserverStatsSQLCompilationsPerSec                       MetricConfig `mapstructure:"sqlserver.stats.sql_compilations_per_sec"`
	SqlserverStatsSQLRecompilationsPerSec                     MetricConfig `mapstructure:"sqlserver.stats.sql_recompilations_per_sec"`
	SqlserverStatsUserErrorsPerSec                            MetricConfig `mapstructure:"sqlserver.stats.user_errors_per_sec"`
	SqlserverTempdbAllocationWaitsMs                          MetricConfig `mapstructure:"sqlserver.tempdb.allocation_waits_ms"`
	SqlserverTempdbCurrentWaiters                             MetricConfig `mapstructure:"sqlserver.tempdb.current_waiters"`
	SqlserverTempdbDataFileCount                              MetricConfig `mapstructure:"sqlserver.tempdb.data_file_count"`
	SqlserverTempdbPagelatchWaitsMs                           MetricConfig `mapstructure:"sqlserver.tempdb.pagelatch_waits_ms"`
	SqlserverTempdbTotalSizeMb                                MetricConfig `mapstructure:"sqlserver.tempdb.total_size_mb"`
	SqlserverThreadpoolCurrentTasks                           MetricConfig `mapstructure:"sqlserver.threadpool.current_tasks"`
	SqlserverThreadpoolMaxWorkers                             MetricConfig `mapstructure:"sqlserver.threadpool.max_workers"`
	SqlserverThreadpoolRunnableTasks                          MetricConfig `mapstructure:"sqlserver.threadpool.runnable_tasks"`
	SqlserverThreadpoolRunningWorkers                         MetricConfig `mapstructure:"sqlserver.threadpool.running_workers"`
	SqlserverThreadpoolUtilizationPercent                     MetricConfig `mapstructure:"sqlserver.threadpool.utilization_percent"`
	SqlserverThreadpoolWaitingTasks                           MetricConfig `mapstructure:"sqlserver.threadpool.waiting_tasks"`
	SqlserverThreadpoolWorkQueueCount                         MetricConfig `mapstructure:"sqlserver.threadpool.work_queue_count"`
	SqlserverUserConnectionsAuthenticationChurnRate           MetricConfig `mapstructure:"sqlserver.user_connections.authentication.churn_rate"`
	SqlserverUserConnectionsAuthenticationLoginsPerSec        MetricConfig `mapstructure:"sqlserver.user_connections.authentication.logins_per_sec"`
	SqlserverUserConnectionsAuthenticationRecentFailedLogins  MetricConfig `mapstructure:"sqlserver.user_connections.authentication.recent_failed_logins"`
	SqlserverUserConnectionsAuthenticationTotalFailedLogins   MetricConfig `mapstructure:"sqlserver.user_connections.authentication.total_failed_logins"`
	SqlserverUserConnectionsAuthenticationUniqueFailedSources MetricConfig `mapstructure:"sqlserver.user_connections.authentication.unique_failed_sources"`
	SqlserverUserConnectionsAuthenticationUniqueFailedUsers   MetricConfig `mapstructure:"sqlserver.user_connections.authentication.unique_failed_users"`
	SqlserverUserConnectionsClientCount                       MetricConfig `mapstructure:"sqlserver.user_connections.client.count"`
	SqlserverUserConnectionsClientUniqueHosts                 MetricConfig `mapstructure:"sqlserver.user_connections.client.unique_hosts"`
	SqlserverUserConnectionsClientUniquePrograms              MetricConfig `mapstructure:"sqlserver.user_connections.client.unique_programs"`
	SqlserverUserConnectionsRunnable                          MetricConfig `mapstructure:"sqlserver.user_connections.runnable"`
	SqlserverUserConnectionsRunning                           MetricConfig `mapstructure:"sqlserver.user_connections.running"`
	SqlserverUserConnectionsSleeping                          MetricConfig `mapstructure:"sqlserver.user_connections.sleeping"`
	SqlserverUserConnectionsSuspended                         MetricConfig `mapstructure:"sqlserver.user_connections.suspended"`
	SqlserverUserConnectionsTotal                             MetricConfig `mapstructure:"sqlserver.user_connections.total"`
	SqlserverUserConnectionsUtilizationActiveRatio            MetricConfig `mapstructure:"sqlserver.user_connections.utilization.active_ratio"`
	SqlserverUserConnectionsUtilizationIdleRatio              MetricConfig `mapstructure:"sqlserver.user_connections.utilization.idle_ratio"`
	SqlserverWaitStatsLatchWaitTimeMs                         MetricConfig `mapstructure:"sqlserver.wait_stats.latch.wait_time_ms"`
	SqlserverWaitStatsLatchWaitingTasksCount                  MetricConfig `mapstructure:"sqlserver.wait_stats.latch.waiting_tasks_count"`
	SqlserverWaitStatsWaitTimeMs                              MetricConfig `mapstructure:"sqlserver.wait_stats.wait_time_ms"`
	SqlserverWaitStatsWaitingTasksCount                       MetricConfig `mapstructure:"sqlserver.wait_stats.waiting_tasks_count"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		SqlserverAccessPageSplitsPerSec: MetricConfig{
			Enabled: true,
		},
		SqlserverActivequeryWaitTimeSeconds: MetricConfig{
			Enabled: true,
		},
		SqlserverBlockingQueryDetails: MetricConfig{
			Enabled: true,
		},
		SqlserverBufferCacheHitRatio: MetricConfig{
			Enabled: true,
		},
		SqlserverBufferCheckpointPagesPerSec: MetricConfig{
			Enabled: true,
		},
		SqlserverBufferPageLifeExpectancy: MetricConfig{
			Enabled: true,
		},
		SqlserverBufferpoolBatchRequestsPerSec: MetricConfig{
			Enabled: true,
		},
		SqlserverBufferpoolPageLifeExpectancyMs: MetricConfig{
			Enabled: true,
		},
		SqlserverConnectionsUser: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseBufferpoolSizePerDatabaseBytes: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseIoStallMs: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseLogBytesFlushedPerSec: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseLogFlushWaitsPerSec: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseLogFlushesPerSec: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseLogTransactionGrowth: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseLogUsedSpaceMb: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseMaxDiskSizeBytes: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabasePageFileAvailableBytes: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabasePageFileTotalBytes: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabasePrincipalsApplicationRoles: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabasePrincipalsOld: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabasePrincipalsOrphanedUsers: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabasePrincipalsRecentlyCreated: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabasePrincipalsRoles: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabasePrincipalsSQLUsers: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabasePrincipalsTotal: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabasePrincipalsUsers: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabasePrincipalsWindowsUsers: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseRoleMembersApplicationRoles: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseRoleMembersCrossRole: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseRoleMembersHighPrivilege: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseRoleMembersUnique: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseRoleMembershipsActive: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseRoleMembershipsCustom: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseRoleMembershipsNested: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseRoleMembershipsTotal: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseRoleMembershipsUsers: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseRolePermissionMemberCount: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseRolePermissionRiskLevel: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseRoleRolesEmpty: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseRoleRolesWithMembers: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseSizeDataMb: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseSizeTotalMb: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseTransactionsActive: MetricConfig{
			Enabled: true,
		},
		SqlserverExecutionPlan: MetricConfig{
			Enabled: true,
		},
		SqlserverFailoverClusterAgClusterType: MetricConfig{
			Enabled: true,
		},
		SqlserverFailoverClusterAgFailureConditionLevel: MetricConfig{
			Enabled: true,
		},
		SqlserverFailoverClusterAgHealthCheckTimeout: MetricConfig{
			Enabled: true,
		},
		SqlserverFailoverClusterAgReplicaRole: MetricConfig{
			Enabled: true,
		},
		SqlserverFailoverClusterAgRequiredSyncSecondaries: MetricConfig{
			Enabled: true,
		},
		SqlserverFailoverClusterAgSynchronizationHealth: MetricConfig{
			Enabled: true,
		},
		SqlserverFailoverClusterFlowControlTimeMs: MetricConfig{
			Enabled: true,
		},
		SqlserverFailoverClusterLogBytesReceivedPerSec: MetricConfig{
			Enabled: true,
		},
		SqlserverFailoverClusterLogSendQueueKb: MetricConfig{
			Enabled: true,
		},
		SqlserverFailoverClusterRedoQueueKb: MetricConfig{
			Enabled: true,
		},
		SqlserverFailoverClusterRedoRateKbSec: MetricConfig{
			Enabled: true,
		},
		SqlserverFailoverClusterTransactionDelayMs: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceBackgroundProcessesCount: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceBlockedProcessesCount: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceBufferPoolHitPercent: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceBufferPoolSize: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceCompilationsPerBatch: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceConnectionsActive: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceDiskInBytes: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceDormantProcessesCount: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceForcedParameterizationsPerSec: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceFullScansRate: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceLockTimeoutsRate: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceMemoryAvailable: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceMemoryTotal: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceMemoryUtilizationPercent: MetricConfig{
			Enabled: true,
		},
		SqlserverInstancePageSplitsPerBatch: MetricConfig{
			Enabled: true,
		},
		SqlserverInstancePreconnectProcessesCount: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceRunnableProcessesCount: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceRunnableTasks: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceRunningProcessesCount: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceSleepingProcessesCount: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceSuspendedProcessesCount: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceTargetMemoryKb: MetricConfig{
			Enabled: true,
		},
		SqlserverInstanceTransactionsPerSec: MetricConfig{
			Enabled: true,
		},
		SqlserverLockModeBulkUpdate: MetricConfig{
			Enabled: true,
		},
		SqlserverLockModeExclusive: MetricConfig{
			Enabled: true,
		},
		SqlserverLockModeIntent: MetricConfig{
			Enabled: true,
		},
		SqlserverLockModeSchema: MetricConfig{
			Enabled: true,
		},
		SqlserverLockModeShared: MetricConfig{
			Enabled: true,
		},
		SqlserverLockModeSharedIntentExclusive: MetricConfig{
			Enabled: true,
		},
		SqlserverLockModeTotal: MetricConfig{
			Enabled: true,
		},
		SqlserverLockModeUpdate: MetricConfig{
			Enabled: true,
		},
		SqlserverLockResourceAllocationUnit: MetricConfig{
			Enabled: true,
		},
		SqlserverLockResourceApplication: MetricConfig{
			Enabled: true,
		},
		SqlserverLockResourceDatabaseLevel: MetricConfig{
			Enabled: true,
		},
		SqlserverLockResourceExtent: MetricConfig{
			Enabled: true,
		},
		SqlserverLockResourceFile: MetricConfig{
			Enabled: true,
		},
		SqlserverLockResourceHobt: MetricConfig{
			Enabled: true,
		},
		SqlserverLockResourceKey: MetricConfig{
			Enabled: true,
		},
		SqlserverLockResourceMetadata: MetricConfig{
			Enabled: true,
		},
		SqlserverLockResourcePage: MetricConfig{
			Enabled: true,
		},
		SqlserverLockResourceRow: MetricConfig{
			Enabled: true,
		},
		SqlserverLockResourceTable: MetricConfig{
			Enabled: true,
		},
		SqlserverLockResourceTotal: MetricConfig{
			Enabled: true,
		},
		SqlserverLockedObject: MetricConfig{
			Enabled: true,
		},
		SqlserverMemoryTarget: MetricConfig{
			Enabled: true,
		},
		SqlserverMemoryTotal: MetricConfig{
			Enabled: true,
		},
		SqlserverPlanAvgElapsedTimeMs: MetricConfig{
			Enabled: true,
		},
		SqlserverSecurityServerPrincipalsCount: MetricConfig{
			Enabled: true,
		},
		SqlserverSecurityServerRoleMembersCount: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryAvgElapsedTimeMs: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryHistoricalAvgElapsedTimeMs: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryHistoricalExecutionCount: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryHistoricalLogicalReads: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryHistoricalPhysicalReads: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryHistoricalRows: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryHistoricalWaitTimeMs: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryHistoricalWorkerTimeMs: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryIntervalAvgElapsedTimeMs: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryIntervalAvgLogicalReads: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryIntervalAvgPhysicalReads: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryIntervalAvgRows: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryIntervalAvgWaitTimeMs: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryIntervalAvgWorkerTimeMs: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryIntervalElapsedTimeMs: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryIntervalExecutionCount: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryIntervalLogicalReads: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryIntervalPhysicalReads: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryIntervalRows: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryIntervalWaitTimeMs: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryIntervalWorkerTimeMs: MetricConfig{
			Enabled: true,
		},
		SqlserverSlowqueryQueryDetails: MetricConfig{
			Enabled: true,
		},
		SqlserverStatsConnections: MetricConfig{
			Enabled: true,
		},
		SqlserverStatsDeadlocksPerSec: MetricConfig{
			Enabled: true,
		},
		SqlserverStatsKillConnectionErrorsPerSec: MetricConfig{
			Enabled: true,
		},
		SqlserverStatsLockWaitsPerSec: MetricConfig{
			Enabled: true,
		},
		SqlserverStatsSQLCompilationsPerSec: MetricConfig{
			Enabled: true,
		},
		SqlserverStatsSQLRecompilationsPerSec: MetricConfig{
			Enabled: true,
		},
		SqlserverStatsUserErrorsPerSec: MetricConfig{
			Enabled: true,
		},
		SqlserverTempdbAllocationWaitsMs: MetricConfig{
			Enabled: true,
		},
		SqlserverTempdbCurrentWaiters: MetricConfig{
			Enabled: true,
		},
		SqlserverTempdbDataFileCount: MetricConfig{
			Enabled: true,
		},
		SqlserverTempdbPagelatchWaitsMs: MetricConfig{
			Enabled: true,
		},
		SqlserverTempdbTotalSizeMb: MetricConfig{
			Enabled: true,
		},
		SqlserverThreadpoolCurrentTasks: MetricConfig{
			Enabled: true,
		},
		SqlserverThreadpoolMaxWorkers: MetricConfig{
			Enabled: true,
		},
		SqlserverThreadpoolRunnableTasks: MetricConfig{
			Enabled: true,
		},
		SqlserverThreadpoolRunningWorkers: MetricConfig{
			Enabled: true,
		},
		SqlserverThreadpoolUtilizationPercent: MetricConfig{
			Enabled: true,
		},
		SqlserverThreadpoolWaitingTasks: MetricConfig{
			Enabled: true,
		},
		SqlserverThreadpoolWorkQueueCount: MetricConfig{
			Enabled: true,
		},
		SqlserverUserConnectionsAuthenticationChurnRate: MetricConfig{
			Enabled: true,
		},
		SqlserverUserConnectionsAuthenticationLoginsPerSec: MetricConfig{
			Enabled: true,
		},
		SqlserverUserConnectionsAuthenticationRecentFailedLogins: MetricConfig{
			Enabled: true,
		},
		SqlserverUserConnectionsAuthenticationTotalFailedLogins: MetricConfig{
			Enabled: true,
		},
		SqlserverUserConnectionsAuthenticationUniqueFailedSources: MetricConfig{
			Enabled: true,
		},
		SqlserverUserConnectionsAuthenticationUniqueFailedUsers: MetricConfig{
			Enabled: true,
		},
		SqlserverUserConnectionsClientCount: MetricConfig{
			Enabled: true,
		},
		SqlserverUserConnectionsClientUniqueHosts: MetricConfig{
			Enabled: true,
		},
		SqlserverUserConnectionsClientUniquePrograms: MetricConfig{
			Enabled: true,
		},
		SqlserverUserConnectionsRunnable: MetricConfig{
			Enabled: true,
		},
		SqlserverUserConnectionsRunning: MetricConfig{
			Enabled: true,
		},
		SqlserverUserConnectionsSleeping: MetricConfig{
			Enabled: true,
		},
		SqlserverUserConnectionsSuspended: MetricConfig{
			Enabled: true,
		},
		SqlserverUserConnectionsTotal: MetricConfig{
			Enabled: true,
		},
		SqlserverUserConnectionsUtilizationActiveRatio: MetricConfig{
			Enabled: true,
		},
		SqlserverUserConnectionsUtilizationIdleRatio: MetricConfig{
			Enabled: true,
		},
		SqlserverWaitStatsLatchWaitTimeMs: MetricConfig{
			Enabled: true,
		},
		SqlserverWaitStatsLatchWaitingTasksCount: MetricConfig{
			Enabled: true,
		},
		SqlserverWaitStatsWaitTimeMs: MetricConfig{
			Enabled: true,
		},
		SqlserverWaitStatsWaitingTasksCount: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for newrelicsqlserver resource attributes.
type ResourceAttributesConfig struct {
	DatabaseName  ResourceAttributeConfig `mapstructure:"database_name"`
	DbSystem      ResourceAttributeConfig `mapstructure:"db.system"`
	EngineEdition ResourceAttributeConfig `mapstructure:"engine_edition"`
	ServerAddress ResourceAttributeConfig `mapstructure:"server.address"`
	ServerPort    ResourceAttributeConfig `mapstructure:"server.port"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		DatabaseName: ResourceAttributeConfig{
			Enabled: true,
		},
		DbSystem: ResourceAttributeConfig{
			Enabled: true,
		},
		EngineEdition: ResourceAttributeConfig{
			Enabled: true,
		},
		ServerAddress: ResourceAttributeConfig{
			Enabled: true,
		},
		ServerPort: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for newrelicsqlserver metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
