// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					SqlserverActivequeryCPUTimeMs:                       MetricConfig{Enabled: true},
					SqlserverActivequeryElapsedTimeMs:                   MetricConfig{Enabled: true},
					SqlserverActivequeryGrantedMemoryPages:              MetricConfig{Enabled: true},
					SqlserverActivequeryLogicalReads:                    MetricConfig{Enabled: true},
					SqlserverActivequeryPhysicalReads:                   MetricConfig{Enabled: true},
					SqlserverActivequeryPhysicalWrites:                  MetricConfig{Enabled: true},
					SqlserverActivequeryRowCount:                        MetricConfig{Enabled: true},
					SqlserverActivequeryWaitTimeS:                       MetricConfig{Enabled: true},
					SqlserverDatabaseBufferpoolSize:                     MetricConfig{Enabled: true},
					SqlserverDatabaseDiskMaxSize:                        MetricConfig{Enabled: true},
					SqlserverDatabaseIoStallTime:                        MetricConfig{Enabled: true},
					SqlserverDatabaseLogTransactionGrowth:               MetricConfig{Enabled: true},
					SqlserverDatabasePagefileAvailable:                  MetricConfig{Enabled: true},
					SqlserverDatabasePagefileTotal:                      MetricConfig{Enabled: true},
					SqlserverDatabasePrincipalsCount:                    MetricConfig{Enabled: true},
					SqlserverDatabaseRoleActiveMemberships:              MetricConfig{Enabled: true},
					SqlserverDatabaseRoleInheritedPermissions:           MetricConfig{Enabled: true},
					SqlserverDatabaseRoleNestingLevel:                   MetricConfig{Enabled: true},
					SqlserverDatabaseRoleTotalMemberships:               MetricConfig{Enabled: true},
					SqlserverDatabaseRoleUniqueMembers:                  MetricConfig{Enabled: true},
					SqlserverFailoverClusterFailureConditionLevel:       MetricConfig{Enabled: true},
					SqlserverFailoverClusterHealthCheckTimeoutMs:        MetricConfig{Enabled: true},
					SqlserverFailoverClusterReplicaRole:                 MetricConfig{Enabled: true},
					SqlserverFailoverClusterSynchronizationHealth:       MetricConfig{Enabled: true},
					SqlserverInstanceActiveConnections:                  MetricConfig{Enabled: true},
					SqlserverInstanceBufferPoolHitPercent:               MetricConfig{Enabled: true},
					SqlserverInstanceBufferPoolSize:                     MetricConfig{Enabled: true},
					SqlserverInstanceDiskMetrics:                        MetricConfig{Enabled: true},
					SqlserverInstanceMemoryAvailable:                    MetricConfig{Enabled: true},
					SqlserverInstanceMemoryTotal:                        MetricConfig{Enabled: true},
					SqlserverInstanceMemoryUtilization:                  MetricConfig{Enabled: true},
					SqlserverInstanceProcessCounts:                      MetricConfig{Enabled: true},
					SqlserverInstanceRunnableTasks:                      MetricConfig{Enabled: true},
					SqlserverLockModeBulkUpdate:                         MetricConfig{Enabled: true},
					SqlserverLockModeExclusive:                          MetricConfig{Enabled: true},
					SqlserverLockModeIntent:                             MetricConfig{Enabled: true},
					SqlserverLockModeSchema:                             MetricConfig{Enabled: true},
					SqlserverLockModeShared:                             MetricConfig{Enabled: true},
					SqlserverLockModeSharedIntentExclusive:              MetricConfig{Enabled: true},
					SqlserverLockModeTotal:                              MetricConfig{Enabled: true},
					SqlserverLockModeUpdate:                             MetricConfig{Enabled: true},
					SqlserverLockResourceAllocationUnit:                 MetricConfig{Enabled: true},
					SqlserverLockResourceApplication:                    MetricConfig{Enabled: true},
					SqlserverLockResourceDatabase:                       MetricConfig{Enabled: true},
					SqlserverLockResourceExtent:                         MetricConfig{Enabled: true},
					SqlserverLockResourceFile:                           MetricConfig{Enabled: true},
					SqlserverLockResourceHobt:                           MetricConfig{Enabled: true},
					SqlserverLockResourceKey:                            MetricConfig{Enabled: true},
					SqlserverLockResourceMetadata:                       MetricConfig{Enabled: true},
					SqlserverLockResourcePage:                           MetricConfig{Enabled: true},
					SqlserverLockResourceRow:                            MetricConfig{Enabled: true},
					SqlserverLockResourceTable:                          MetricConfig{Enabled: true},
					SqlserverLockResourceTotal:                          MetricConfig{Enabled: true},
					SqlserverLockedObject:                               MetricConfig{Enabled: true},
					SqlserverPlanAvgElapsedTimeMs:                       MetricConfig{Enabled: true},
					SqlserverPlanAvgLogicalReads:                        MetricConfig{Enabled: true},
					SqlserverPlanAvgLogicalWrites:                       MetricConfig{Enabled: true},
					SqlserverPlanAvgWorkerTimeMs:                        MetricConfig{Enabled: true},
					SqlserverPlanExecutionCount:                         MetricConfig{Enabled: true},
					SqlserverPlanTotalElapsedTimeMs:                     MetricConfig{Enabled: true},
					SqlserverSecurityPrincipalsCount:                    MetricConfig{Enabled: true},
					SqlserverSecurityRoleMembersCount:                   MetricConfig{Enabled: true},
					SqlserverSlowqueryAvgCPUTimeMs:                      MetricConfig{Enabled: true},
					SqlserverSlowqueryAvgDiskReads:                      MetricConfig{Enabled: true},
					SqlserverSlowqueryAvgDiskWrites:                     MetricConfig{Enabled: true},
					SqlserverSlowqueryAvgRowsProcessed:                  MetricConfig{Enabled: true},
					SqlserverSlowqueryHistoricalAvgElapsedTimeMs:        MetricConfig{Enabled: true},
					SqlserverSlowqueryHistoricalExecutionCount:          MetricConfig{Enabled: true},
					SqlserverSlowqueryIntervalAvgElapsedTimeMs:          MetricConfig{Enabled: true},
					SqlserverSlowqueryIntervalExecutionCount:            MetricConfig{Enabled: true},
					SqlserverSlowqueryLastDop:                           MetricConfig{Enabled: true},
					SqlserverSlowqueryLastGrantKb:                       MetricConfig{Enabled: true},
					SqlserverSlowqueryLastSpills:                        MetricConfig{Enabled: true},
					SqlserverTempdbAllocationWaits:                      MetricConfig{Enabled: true},
					SqlserverTempdbCurrentWaiters:                       MetricConfig{Enabled: true},
					SqlserverTempdbDataFileCount:                        MetricConfig{Enabled: true},
					SqlserverTempdbPagelatchWaits:                       MetricConfig{Enabled: true},
					SqlserverTempdbTotalSize:                            MetricConfig{Enabled: true},
					SqlserverThreadpoolCurrentTasks:                     MetricConfig{Enabled: true},
					SqlserverThreadpoolMaxWorkers:                       MetricConfig{Enabled: true},
					SqlserverThreadpoolRunnableTasks:                    MetricConfig{Enabled: true},
					SqlserverThreadpoolRunningWorkers:                   MetricConfig{Enabled: true},
					SqlserverThreadpoolUtilization:                      MetricConfig{Enabled: true},
					SqlserverThreadpoolWaitingTasks:                     MetricConfig{Enabled: true},
					SqlserverThreadpoolWorkQueueCount:                   MetricConfig{Enabled: true},
					SqlserverUserConnectionsAuthenticationFailed:        MetricConfig{Enabled: true},
					SqlserverUserConnectionsAuthenticationLoginsPerSec:  MetricConfig{Enabled: true},
					SqlserverUserConnectionsAuthenticationLogoutsPerSec: MetricConfig{Enabled: true},
					SqlserverUserConnectionsByStatus:                    MetricConfig{Enabled: true},
					SqlserverUserConnectionsTotal:                       MetricConfig{Enabled: true},
					SqlserverUserConnectionsUtilizationActiveRatio:      MetricConfig{Enabled: true},
					SqlserverUserConnectionsUtilizationEfficiency:       MetricConfig{Enabled: true},
					SqlserverWaitStatsLatchWaitTime:                     MetricConfig{Enabled: true},
					SqlserverWaitStatsLatchWaitingTasksCount:            MetricConfig{Enabled: true},
					SqlserverWaitStatsWaitTime:                          MetricConfig{Enabled: true},
					SqlserverWaitStatsWaitingTasksCount:                 MetricConfig{Enabled: true},
				},
				ResourceAttributes: ResourceAttributesConfig{
					DatabaseName:  ResourceAttributeConfig{Enabled: true},
					DbSystem:      ResourceAttributeConfig{Enabled: true},
					ServerAddress: ResourceAttributeConfig{Enabled: true},
					ServerPort:    ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					SqlserverActivequeryCPUTimeMs:                       MetricConfig{Enabled: false},
					SqlserverActivequeryElapsedTimeMs:                   MetricConfig{Enabled: false},
					SqlserverActivequeryGrantedMemoryPages:              MetricConfig{Enabled: false},
					SqlserverActivequeryLogicalReads:                    MetricConfig{Enabled: false},
					SqlserverActivequeryPhysicalReads:                   MetricConfig{Enabled: false},
					SqlserverActivequeryPhysicalWrites:                  MetricConfig{Enabled: false},
					SqlserverActivequeryRowCount:                        MetricConfig{Enabled: false},
					SqlserverActivequeryWaitTimeS:                       MetricConfig{Enabled: false},
					SqlserverDatabaseBufferpoolSize:                     MetricConfig{Enabled: false},
					SqlserverDatabaseDiskMaxSize:                        MetricConfig{Enabled: false},
					SqlserverDatabaseIoStallTime:                        MetricConfig{Enabled: false},
					SqlserverDatabaseLogTransactionGrowth:               MetricConfig{Enabled: false},
					SqlserverDatabasePagefileAvailable:                  MetricConfig{Enabled: false},
					SqlserverDatabasePagefileTotal:                      MetricConfig{Enabled: false},
					SqlserverDatabasePrincipalsCount:                    MetricConfig{Enabled: false},
					SqlserverDatabaseRoleActiveMemberships:              MetricConfig{Enabled: false},
					SqlserverDatabaseRoleInheritedPermissions:           MetricConfig{Enabled: false},
					SqlserverDatabaseRoleNestingLevel:                   MetricConfig{Enabled: false},
					SqlserverDatabaseRoleTotalMemberships:               MetricConfig{Enabled: false},
					SqlserverDatabaseRoleUniqueMembers:                  MetricConfig{Enabled: false},
					SqlserverFailoverClusterFailureConditionLevel:       MetricConfig{Enabled: false},
					SqlserverFailoverClusterHealthCheckTimeoutMs:        MetricConfig{Enabled: false},
					SqlserverFailoverClusterReplicaRole:                 MetricConfig{Enabled: false},
					SqlserverFailoverClusterSynchronizationHealth:       MetricConfig{Enabled: false},
					SqlserverInstanceActiveConnections:                  MetricConfig{Enabled: false},
					SqlserverInstanceBufferPoolHitPercent:               MetricConfig{Enabled: false},
					SqlserverInstanceBufferPoolSize:                     MetricConfig{Enabled: false},
					SqlserverInstanceDiskMetrics:                        MetricConfig{Enabled: false},
					SqlserverInstanceMemoryAvailable:                    MetricConfig{Enabled: false},
					SqlserverInstanceMemoryTotal:                        MetricConfig{Enabled: false},
					SqlserverInstanceMemoryUtilization:                  MetricConfig{Enabled: false},
					SqlserverInstanceProcessCounts:                      MetricConfig{Enabled: false},
					SqlserverInstanceRunnableTasks:                      MetricConfig{Enabled: false},
					SqlserverLockModeBulkUpdate:                         MetricConfig{Enabled: false},
					SqlserverLockModeExclusive:                          MetricConfig{Enabled: false},
					SqlserverLockModeIntent:                             MetricConfig{Enabled: false},
					SqlserverLockModeSchema:                             MetricConfig{Enabled: false},
					SqlserverLockModeShared:                             MetricConfig{Enabled: false},
					SqlserverLockModeSharedIntentExclusive:              MetricConfig{Enabled: false},
					SqlserverLockModeTotal:                              MetricConfig{Enabled: false},
					SqlserverLockModeUpdate:                             MetricConfig{Enabled: false},
					SqlserverLockResourceAllocationUnit:                 MetricConfig{Enabled: false},
					SqlserverLockResourceApplication:                    MetricConfig{Enabled: false},
					SqlserverLockResourceDatabase:                       MetricConfig{Enabled: false},
					SqlserverLockResourceExtent:                         MetricConfig{Enabled: false},
					SqlserverLockResourceFile:                           MetricConfig{Enabled: false},
					SqlserverLockResourceHobt:                           MetricConfig{Enabled: false},
					SqlserverLockResourceKey:                            MetricConfig{Enabled: false},
					SqlserverLockResourceMetadata:                       MetricConfig{Enabled: false},
					SqlserverLockResourcePage:                           MetricConfig{Enabled: false},
					SqlserverLockResourceRow:                            MetricConfig{Enabled: false},
					SqlserverLockResourceTable:                          MetricConfig{Enabled: false},
					SqlserverLockResourceTotal:                          MetricConfig{Enabled: false},
					SqlserverLockedObject:                               MetricConfig{Enabled: false},
					SqlserverPlanAvgElapsedTimeMs:                       MetricConfig{Enabled: false},
					SqlserverPlanAvgLogicalReads:                        MetricConfig{Enabled: false},
					SqlserverPlanAvgLogicalWrites:                       MetricConfig{Enabled: false},
					SqlserverPlanAvgWorkerTimeMs:                        MetricConfig{Enabled: false},
					SqlserverPlanExecutionCount:                         MetricConfig{Enabled: false},
					SqlserverPlanTotalElapsedTimeMs:                     MetricConfig{Enabled: false},
					SqlserverSecurityPrincipalsCount:                    MetricConfig{Enabled: false},
					SqlserverSecurityRoleMembersCount:                   MetricConfig{Enabled: false},
					SqlserverSlowqueryAvgCPUTimeMs:                      MetricConfig{Enabled: false},
					SqlserverSlowqueryAvgDiskReads:                      MetricConfig{Enabled: false},
					SqlserverSlowqueryAvgDiskWrites:                     MetricConfig{Enabled: false},
					SqlserverSlowqueryAvgRowsProcessed:                  MetricConfig{Enabled: false},
					SqlserverSlowqueryHistoricalAvgElapsedTimeMs:        MetricConfig{Enabled: false},
					SqlserverSlowqueryHistoricalExecutionCount:          MetricConfig{Enabled: false},
					SqlserverSlowqueryIntervalAvgElapsedTimeMs:          MetricConfig{Enabled: false},
					SqlserverSlowqueryIntervalExecutionCount:            MetricConfig{Enabled: false},
					SqlserverSlowqueryLastDop:                           MetricConfig{Enabled: false},
					SqlserverSlowqueryLastGrantKb:                       MetricConfig{Enabled: false},
					SqlserverSlowqueryLastSpills:                        MetricConfig{Enabled: false},
					SqlserverTempdbAllocationWaits:                      MetricConfig{Enabled: false},
					SqlserverTempdbCurrentWaiters:                       MetricConfig{Enabled: false},
					SqlserverTempdbDataFileCount:                        MetricConfig{Enabled: false},
					SqlserverTempdbPagelatchWaits:                       MetricConfig{Enabled: false},
					SqlserverTempdbTotalSize:                            MetricConfig{Enabled: false},
					SqlserverThreadpoolCurrentTasks:                     MetricConfig{Enabled: false},
					SqlserverThreadpoolMaxWorkers:                       MetricConfig{Enabled: false},
					SqlserverThreadpoolRunnableTasks:                    MetricConfig{Enabled: false},
					SqlserverThreadpoolRunningWorkers:                   MetricConfig{Enabled: false},
					SqlserverThreadpoolUtilization:                      MetricConfig{Enabled: false},
					SqlserverThreadpoolWaitingTasks:                     MetricConfig{Enabled: false},
					SqlserverThreadpoolWorkQueueCount:                   MetricConfig{Enabled: false},
					SqlserverUserConnectionsAuthenticationFailed:        MetricConfig{Enabled: false},
					SqlserverUserConnectionsAuthenticationLoginsPerSec:  MetricConfig{Enabled: false},
					SqlserverUserConnectionsAuthenticationLogoutsPerSec: MetricConfig{Enabled: false},
					SqlserverUserConnectionsByStatus:                    MetricConfig{Enabled: false},
					SqlserverUserConnectionsTotal:                       MetricConfig{Enabled: false},
					SqlserverUserConnectionsUtilizationActiveRatio:      MetricConfig{Enabled: false},
					SqlserverUserConnectionsUtilizationEfficiency:       MetricConfig{Enabled: false},
					SqlserverWaitStatsLatchWaitTime:                     MetricConfig{Enabled: false},
					SqlserverWaitStatsLatchWaitingTasksCount:            MetricConfig{Enabled: false},
					SqlserverWaitStatsWaitTime:                          MetricConfig{Enabled: false},
					SqlserverWaitStatsWaitingTasksCount:                 MetricConfig{Enabled: false},
				},
				ResourceAttributes: ResourceAttributesConfig{
					DatabaseName:  ResourceAttributeConfig{Enabled: false},
					DbSystem:      ResourceAttributeConfig{Enabled: false},
					ServerAddress: ResourceAttributeConfig{Enabled: false},
					ServerPort:    ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				DatabaseName:  ResourceAttributeConfig{Enabled: true},
				DbSystem:      ResourceAttributeConfig{Enabled: true},
				ServerAddress: ResourceAttributeConfig{Enabled: true},
				ServerPort:    ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				DatabaseName:  ResourceAttributeConfig{Enabled: false},
				DbSystem:      ResourceAttributeConfig{Enabled: false},
				ServerAddress: ResourceAttributeConfig{Enabled: false},
				ServerPort:    ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
