// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
		{
			name:        "filter_set_include",
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "filter_set_exclude",
			resAttrsSet: testDataSetAll,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0

			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverActivequeryCPUTimeMsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverActivequeryElapsedTimeMsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverActivequeryGrantedMemoryPagesDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverActivequeryLogicalReadsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverActivequeryPhysicalReadsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverActivequeryPhysicalWritesDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverActivequeryRowCountDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverActivequeryWaitTimeSDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverDatabaseBufferpoolSizeDataPoint(ts, 1, "db_name-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverDatabaseDiskMaxSizeDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverDatabaseIoStallTimeDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverDatabaseLogTransactionGrowthDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverDatabasePagefileAvailableDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverDatabasePagefileTotalDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverDatabasePrincipalsCountDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverDatabaseRoleActiveMembershipsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverDatabaseRoleInheritedPermissionsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverDatabaseRoleNestingLevelDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverDatabaseRoleTotalMembershipsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverDatabaseRoleUniqueMembersDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverFailoverClusterFailureConditionLevelDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverFailoverClusterHealthCheckTimeoutMsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverFailoverClusterReplicaRoleDataPoint(ts, 1, "replica_id-val", "role-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverFailoverClusterSynchronizationHealthDataPoint(ts, 1, "replica_id-val", "synchronization_health-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverInstanceActiveConnectionsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverInstanceBufferPoolHitPercentDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverInstanceBufferPoolSizeDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverInstanceDiskMetricsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverInstanceMemoryAvailableDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverInstanceMemoryTotalDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverInstanceMemoryUtilizationDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverInstanceProcessCountsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverInstanceRunnableTasksDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockModeBulkUpdateDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockModeExclusiveDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockModeIntentDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockModeSchemaDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockModeSharedDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockModeSharedIntentExclusiveDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockModeTotalDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockModeUpdateDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockResourceAllocationUnitDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockResourceApplicationDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockResourceDatabaseDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockResourceExtentDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockResourceFileDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockResourceHobtDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockResourceKeyDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockResourceMetadataDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockResourcePageDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockResourceRowDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockResourceTableDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockResourceTotalDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverLockedObjectDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverPlanAvgElapsedTimeMsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverPlanAvgLogicalReadsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverPlanAvgLogicalWritesDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverPlanAvgWorkerTimeMsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverPlanExecutionCountDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverPlanTotalElapsedTimeMsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverSecurityPrincipalsCountDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverSecurityRoleMembersCountDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverSlowqueryAvgCPUTimeMsDataPoint(ts, 1, "query_id-val", "database_name-val", "query_text-val", "last_execution_timestamp-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverSlowqueryAvgDiskReadsDataPoint(ts, 1, "query_id-val", "database_name-val", "query_text-val", "last_execution_timestamp-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverSlowqueryAvgDiskWritesDataPoint(ts, 1, "query_id-val", "database_name-val", "query_text-val", "last_execution_timestamp-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverSlowqueryAvgRowsProcessedDataPoint(ts, 1, "query_id-val", "database_name-val", "query_text-val", "last_execution_timestamp-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverSlowqueryHistoricalAvgElapsedTimeMsDataPoint(ts, 1, "query_id-val", "database_name-val", "query_text-val", "last_execution_timestamp-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverSlowqueryHistoricalExecutionCountDataPoint(ts, 1, "query_id-val", "database_name-val", "query_text-val", "last_execution_timestamp-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverSlowqueryIntervalAvgElapsedTimeMsDataPoint(ts, 1, "query_id-val", "database_name-val", "query_text-val", "last_execution_timestamp-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverSlowqueryIntervalExecutionCountDataPoint(ts, 1, "query_id-val", "database_name-val", "query_text-val", "last_execution_timestamp-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverSlowqueryLastDopDataPoint(ts, 1, "query_id-val", "database_name-val", "query_text-val", "last_execution_timestamp-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverSlowqueryLastGrantKbDataPoint(ts, 1, "query_id-val", "database_name-val", "query_text-val", "last_execution_timestamp-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverSlowqueryLastSpillsDataPoint(ts, 1, "query_id-val", "database_name-val", "query_text-val", "last_execution_timestamp-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverTempdbAllocationWaitsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverTempdbCurrentWaitersDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverTempdbDataFileCountDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverTempdbPagelatchWaitsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverTempdbTotalSizeDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverThreadpoolCurrentTasksDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverThreadpoolMaxWorkersDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverThreadpoolRunnableTasksDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverThreadpoolRunningWorkersDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverThreadpoolUtilizationDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverThreadpoolWaitingTasksDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverThreadpoolWorkQueueCountDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverUserConnectionsAuthenticationFailedDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverUserConnectionsAuthenticationLoginsPerSecDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverUserConnectionsAuthenticationLogoutsPerSecDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverUserConnectionsByStatusDataPoint(ts, 1, "connection_status-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverUserConnectionsTotalDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverUserConnectionsUtilizationActiveRatioDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverUserConnectionsUtilizationEfficiencyDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverWaitStatsLatchWaitTimeDataPoint(ts, 1, "latch_class-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverWaitStatsLatchWaitingTasksCountDataPoint(ts, 1, "latch_class-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverWaitStatsWaitTimeDataPoint(ts, 1, "wait_type-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSqlserverWaitStatsWaitingTasksCountDataPoint(ts, 1, "wait_type-val")

			rb := mb.NewResourceBuilder()
			rb.SetDatabaseName("database_name-val")
			rb.SetDbSystem("db.system-val")
			rb.SetServerAddress("server.address-val")
			rb.SetServerPort("server.port-val")
			res := rb.Emit()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			assert.Equal(t, 1, metrics.ResourceMetrics().Len())
			rm := metrics.ResourceMetrics().At(0)
			assert.Equal(t, res, rm.Resource())
			assert.Equal(t, 1, rm.ScopeMetrics().Len())
			ms := rm.ScopeMetrics().At(0).Metrics()
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, ms.Len())
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, ms.Len())
			}
			validatedMetrics := make(map[string]bool)
			for i := 0; i < ms.Len(); i++ {
				switch ms.At(i).Name() {
				case "sqlserver.activequery.cpu_time_ms":
					assert.False(t, validatedMetrics["sqlserver.activequery.cpu_time_ms"], "Found a duplicate in the metrics slice: sqlserver.activequery.cpu_time_ms")
					validatedMetrics["sqlserver.activequery.cpu_time_ms"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "CPU time consumed by active query", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.activequery.elapsed_time_ms":
					assert.False(t, validatedMetrics["sqlserver.activequery.elapsed_time_ms"], "Found a duplicate in the metrics slice: sqlserver.activequery.elapsed_time_ms")
					validatedMetrics["sqlserver.activequery.elapsed_time_ms"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Total elapsed time for active query", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.activequery.granted_memory_pages":
					assert.False(t, validatedMetrics["sqlserver.activequery.granted_memory_pages"], "Found a duplicate in the metrics slice: sqlserver.activequery.granted_memory_pages")
					validatedMetrics["sqlserver.activequery.granted_memory_pages"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Granted query memory in pages", ms.At(i).Description())
					assert.Equal(t, "{pages}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.activequery.logical_reads":
					assert.False(t, validatedMetrics["sqlserver.activequery.logical_reads"], "Found a duplicate in the metrics slice: sqlserver.activequery.logical_reads")
					validatedMetrics["sqlserver.activequery.logical_reads"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Logical reads by active query", ms.At(i).Description())
					assert.Equal(t, "{reads}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.activequery.physical_reads":
					assert.False(t, validatedMetrics["sqlserver.activequery.physical_reads"], "Found a duplicate in the metrics slice: sqlserver.activequery.physical_reads")
					validatedMetrics["sqlserver.activequery.physical_reads"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Physical reads by active query", ms.At(i).Description())
					assert.Equal(t, "{reads}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.activequery.physical_writes":
					assert.False(t, validatedMetrics["sqlserver.activequery.physical_writes"], "Found a duplicate in the metrics slice: sqlserver.activequery.physical_writes")
					validatedMetrics["sqlserver.activequery.physical_writes"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Writes by active query", ms.At(i).Description())
					assert.Equal(t, "{writes}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.activequery.row_count":
					assert.False(t, validatedMetrics["sqlserver.activequery.row_count"], "Found a duplicate in the metrics slice: sqlserver.activequery.row_count")
					validatedMetrics["sqlserver.activequery.row_count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Rows returned by active query", ms.At(i).Description())
					assert.Equal(t, "{rows}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.activequery.wait_time_s":
					assert.False(t, validatedMetrics["sqlserver.activequery.wait_time_s"], "Found a duplicate in the metrics slice: sqlserver.activequery.wait_time_s")
					validatedMetrics["sqlserver.activequery.wait_time_s"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Current wait time for active query", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "sqlserver.database.bufferpool.size":
					assert.False(t, validatedMetrics["sqlserver.database.bufferpool.size"], "Found a duplicate in the metrics slice: sqlserver.database.bufferpool.size")
					validatedMetrics["sqlserver.database.bufferpool.size"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Size of buffer pool allocated per database", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("db_name")
					assert.True(t, ok)
					assert.Equal(t, "db_name-val", attrVal.Str())
				case "sqlserver.database.disk.max_size":
					assert.False(t, validatedMetrics["sqlserver.database.disk.max_size"], "Found a duplicate in the metrics slice: sqlserver.database.disk.max_size")
					validatedMetrics["sqlserver.database.disk.max_size"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Maximum disk size for database (Azure SQL Database)", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.database.io.stall_time":
					assert.False(t, validatedMetrics["sqlserver.database.io.stall_time"], "Found a duplicate in the metrics slice: sqlserver.database.io.stall_time")
					validatedMetrics["sqlserver.database.io.stall_time"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "I/O stall time in milliseconds", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.database.log.transaction_growth":
					assert.False(t, validatedMetrics["sqlserver.database.log.transaction_growth"], "Found a duplicate in the metrics slice: sqlserver.database.log.transaction_growth")
					validatedMetrics["sqlserver.database.log.transaction_growth"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Transaction log growth count", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.database.pagefile.available":
					assert.False(t, validatedMetrics["sqlserver.database.pagefile.available"], "Found a duplicate in the metrics slice: sqlserver.database.pagefile.available")
					validatedMetrics["sqlserver.database.pagefile.available"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Available page file space", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.database.pagefile.total":
					assert.False(t, validatedMetrics["sqlserver.database.pagefile.total"], "Found a duplicate in the metrics slice: sqlserver.database.pagefile.total")
					validatedMetrics["sqlserver.database.pagefile.total"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Total page file space", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.database.principals.count":
					assert.False(t, validatedMetrics["sqlserver.database.principals.count"], "Found a duplicate in the metrics slice: sqlserver.database.principals.count")
					validatedMetrics["sqlserver.database.principals.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of database principals", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.database.role.active_memberships":
					assert.False(t, validatedMetrics["sqlserver.database.role.active_memberships"], "Found a duplicate in the metrics slice: sqlserver.database.role.active_memberships")
					validatedMetrics["sqlserver.database.role.active_memberships"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Active role memberships", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.database.role.inherited_permissions":
					assert.False(t, validatedMetrics["sqlserver.database.role.inherited_permissions"], "Found a duplicate in the metrics slice: sqlserver.database.role.inherited_permissions")
					validatedMetrics["sqlserver.database.role.inherited_permissions"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Inherited permissions count", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.database.role.nesting_level":
					assert.False(t, validatedMetrics["sqlserver.database.role.nesting_level"], "Found a duplicate in the metrics slice: sqlserver.database.role.nesting_level")
					validatedMetrics["sqlserver.database.role.nesting_level"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Role nesting depth", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.database.role.total_memberships":
					assert.False(t, validatedMetrics["sqlserver.database.role.total_memberships"], "Found a duplicate in the metrics slice: sqlserver.database.role.total_memberships")
					validatedMetrics["sqlserver.database.role.total_memberships"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Total role memberships", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.database.role.unique_members":
					assert.False(t, validatedMetrics["sqlserver.database.role.unique_members"], "Found a duplicate in the metrics slice: sqlserver.database.role.unique_members")
					validatedMetrics["sqlserver.database.role.unique_members"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Unique role members", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.failover_cluster.failure_condition_level":
					assert.False(t, validatedMetrics["sqlserver.failover_cluster.failure_condition_level"], "Found a duplicate in the metrics slice: sqlserver.failover_cluster.failure_condition_level")
					validatedMetrics["sqlserver.failover_cluster.failure_condition_level"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "AG failure condition level setting", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.failover_cluster.health_check_timeout_ms":
					assert.False(t, validatedMetrics["sqlserver.failover_cluster.health_check_timeout_ms"], "Found a duplicate in the metrics slice: sqlserver.failover_cluster.health_check_timeout_ms")
					validatedMetrics["sqlserver.failover_cluster.health_check_timeout_ms"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "AG health check timeout", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.failover_cluster.replica_role":
					assert.False(t, validatedMetrics["sqlserver.failover_cluster.replica_role"], "Found a duplicate in the metrics slice: sqlserver.failover_cluster.replica_role")
					validatedMetrics["sqlserver.failover_cluster.replica_role"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Availability Group replica role indicator", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("replica_id")
					assert.True(t, ok)
					assert.Equal(t, "replica_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("role")
					assert.True(t, ok)
					assert.Equal(t, "role-val", attrVal.Str())
				case "sqlserver.failover_cluster.synchronization_health":
					assert.False(t, validatedMetrics["sqlserver.failover_cluster.synchronization_health"], "Found a duplicate in the metrics slice: sqlserver.failover_cluster.synchronization_health")
					validatedMetrics["sqlserver.failover_cluster.synchronization_health"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "AG synchronization health status", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("replica_id")
					assert.True(t, ok)
					assert.Equal(t, "replica_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("synchronization_health")
					assert.True(t, ok)
					assert.Equal(t, "synchronization_health-val", attrVal.Str())
				case "sqlserver.instance.active_connections":
					assert.False(t, validatedMetrics["sqlserver.instance.active_connections"], "Found a duplicate in the metrics slice: sqlserver.instance.active_connections")
					validatedMetrics["sqlserver.instance.active_connections"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of active connections", ms.At(i).Description())
					assert.Equal(t, "{connections}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.instance.buffer_pool.hit_percent":
					assert.False(t, validatedMetrics["sqlserver.instance.buffer_pool.hit_percent"], "Found a duplicate in the metrics slice: sqlserver.instance.buffer_pool.hit_percent")
					validatedMetrics["sqlserver.instance.buffer_pool.hit_percent"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Buffer pool cache hit ratio percentage", ms.At(i).Description())
					assert.Equal(t, "%", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "sqlserver.instance.buffer_pool.size":
					assert.False(t, validatedMetrics["sqlserver.instance.buffer_pool.size"], "Found a duplicate in the metrics slice: sqlserver.instance.buffer_pool.size")
					validatedMetrics["sqlserver.instance.buffer_pool.size"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Buffer pool size in bytes", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.instance.disk_metrics":
					assert.False(t, validatedMetrics["sqlserver.instance.disk_metrics"], "Found a duplicate in the metrics slice: sqlserver.instance.disk_metrics")
					validatedMetrics["sqlserver.instance.disk_metrics"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Instance-level disk I/O metrics", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.instance.memory.available":
					assert.False(t, validatedMetrics["sqlserver.instance.memory.available"], "Found a duplicate in the metrics slice: sqlserver.instance.memory.available")
					validatedMetrics["sqlserver.instance.memory.available"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Available physical memory", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.instance.memory.total":
					assert.False(t, validatedMetrics["sqlserver.instance.memory.total"], "Found a duplicate in the metrics slice: sqlserver.instance.memory.total")
					validatedMetrics["sqlserver.instance.memory.total"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Total physical memory available to SQL Server", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.instance.memory.utilization":
					assert.False(t, validatedMetrics["sqlserver.instance.memory.utilization"], "Found a duplicate in the metrics slice: sqlserver.instance.memory.utilization")
					validatedMetrics["sqlserver.instance.memory.utilization"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Memory utilization percentage", ms.At(i).Description())
					assert.Equal(t, "%", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "sqlserver.instance.process_counts":
					assert.False(t, validatedMetrics["sqlserver.instance.process_counts"], "Found a duplicate in the metrics slice: sqlserver.instance.process_counts")
					validatedMetrics["sqlserver.instance.process_counts"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of processes/connections", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.instance.runnable_tasks":
					assert.False(t, validatedMetrics["sqlserver.instance.runnable_tasks"], "Found a duplicate in the metrics slice: sqlserver.instance.runnable_tasks")
					validatedMetrics["sqlserver.instance.runnable_tasks"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of runnable tasks waiting for CPU", ms.At(i).Description())
					assert.Equal(t, "{tasks}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.mode.bulk_update":
					assert.False(t, validatedMetrics["sqlserver.lock.mode.bulk_update"], "Found a duplicate in the metrics slice: sqlserver.lock.mode.bulk_update")
					validatedMetrics["sqlserver.lock.mode.bulk_update"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of bulk update locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.mode.exclusive":
					assert.False(t, validatedMetrics["sqlserver.lock.mode.exclusive"], "Found a duplicate in the metrics slice: sqlserver.lock.mode.exclusive")
					validatedMetrics["sqlserver.lock.mode.exclusive"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of exclusive locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.mode.intent":
					assert.False(t, validatedMetrics["sqlserver.lock.mode.intent"], "Found a duplicate in the metrics slice: sqlserver.lock.mode.intent")
					validatedMetrics["sqlserver.lock.mode.intent"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of intent locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.mode.schema":
					assert.False(t, validatedMetrics["sqlserver.lock.mode.schema"], "Found a duplicate in the metrics slice: sqlserver.lock.mode.schema")
					validatedMetrics["sqlserver.lock.mode.schema"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of schema locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.mode.shared":
					assert.False(t, validatedMetrics["sqlserver.lock.mode.shared"], "Found a duplicate in the metrics slice: sqlserver.lock.mode.shared")
					validatedMetrics["sqlserver.lock.mode.shared"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of shared locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.mode.shared_intent_exclusive":
					assert.False(t, validatedMetrics["sqlserver.lock.mode.shared_intent_exclusive"], "Found a duplicate in the metrics slice: sqlserver.lock.mode.shared_intent_exclusive")
					validatedMetrics["sqlserver.lock.mode.shared_intent_exclusive"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of shared intent exclusive locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.mode.total":
					assert.False(t, validatedMetrics["sqlserver.lock.mode.total"], "Found a duplicate in the metrics slice: sqlserver.lock.mode.total")
					validatedMetrics["sqlserver.lock.mode.total"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Total active locks by mode", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.mode.update":
					assert.False(t, validatedMetrics["sqlserver.lock.mode.update"], "Found a duplicate in the metrics slice: sqlserver.lock.mode.update")
					validatedMetrics["sqlserver.lock.mode.update"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of update locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.resource.allocation_unit":
					assert.False(t, validatedMetrics["sqlserver.lock.resource.allocation_unit"], "Found a duplicate in the metrics slice: sqlserver.lock.resource.allocation_unit")
					validatedMetrics["sqlserver.lock.resource.allocation_unit"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of allocation unit locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.resource.application":
					assert.False(t, validatedMetrics["sqlserver.lock.resource.application"], "Found a duplicate in the metrics slice: sqlserver.lock.resource.application")
					validatedMetrics["sqlserver.lock.resource.application"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of application locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.resource.database":
					assert.False(t, validatedMetrics["sqlserver.lock.resource.database"], "Found a duplicate in the metrics slice: sqlserver.lock.resource.database")
					validatedMetrics["sqlserver.lock.resource.database"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of database-level locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.resource.extent":
					assert.False(t, validatedMetrics["sqlserver.lock.resource.extent"], "Found a duplicate in the metrics slice: sqlserver.lock.resource.extent")
					validatedMetrics["sqlserver.lock.resource.extent"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of extent-level locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.resource.file":
					assert.False(t, validatedMetrics["sqlserver.lock.resource.file"], "Found a duplicate in the metrics slice: sqlserver.lock.resource.file")
					validatedMetrics["sqlserver.lock.resource.file"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of file-level locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.resource.hobt":
					assert.False(t, validatedMetrics["sqlserver.lock.resource.hobt"], "Found a duplicate in the metrics slice: sqlserver.lock.resource.hobt")
					validatedMetrics["sqlserver.lock.resource.hobt"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of heap or B-tree locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.resource.key":
					assert.False(t, validatedMetrics["sqlserver.lock.resource.key"], "Found a duplicate in the metrics slice: sqlserver.lock.resource.key")
					validatedMetrics["sqlserver.lock.resource.key"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of key-level locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.resource.metadata":
					assert.False(t, validatedMetrics["sqlserver.lock.resource.metadata"], "Found a duplicate in the metrics slice: sqlserver.lock.resource.metadata")
					validatedMetrics["sqlserver.lock.resource.metadata"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of metadata locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.resource.page":
					assert.False(t, validatedMetrics["sqlserver.lock.resource.page"], "Found a duplicate in the metrics slice: sqlserver.lock.resource.page")
					validatedMetrics["sqlserver.lock.resource.page"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of page-level locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.resource.row":
					assert.False(t, validatedMetrics["sqlserver.lock.resource.row"], "Found a duplicate in the metrics slice: sqlserver.lock.resource.row")
					validatedMetrics["sqlserver.lock.resource.row"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of row-level locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.resource.table":
					assert.False(t, validatedMetrics["sqlserver.lock.resource.table"], "Found a duplicate in the metrics slice: sqlserver.lock.resource.table")
					validatedMetrics["sqlserver.lock.resource.table"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of table-level locks", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.lock.resource.total":
					assert.False(t, validatedMetrics["sqlserver.lock.resource.total"], "Found a duplicate in the metrics slice: sqlserver.lock.resource.total")
					validatedMetrics["sqlserver.lock.resource.total"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Total active locks in the database", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.locked_object":
					assert.False(t, validatedMetrics["sqlserver.locked_object"], "Found a duplicate in the metrics slice: sqlserver.locked_object")
					validatedMetrics["sqlserver.locked_object"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Information about locked database objects", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.plan.avg_elapsed_time_ms":
					assert.False(t, validatedMetrics["sqlserver.plan.avg_elapsed_time_ms"], "Found a duplicate in the metrics slice: sqlserver.plan.avg_elapsed_time_ms")
					validatedMetrics["sqlserver.plan.avg_elapsed_time_ms"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average elapsed time for plan", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "sqlserver.plan.avg_logical_reads":
					assert.False(t, validatedMetrics["sqlserver.plan.avg_logical_reads"], "Found a duplicate in the metrics slice: sqlserver.plan.avg_logical_reads")
					validatedMetrics["sqlserver.plan.avg_logical_reads"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average logical page reads", ms.At(i).Description())
					assert.Equal(t, "{reads}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "sqlserver.plan.avg_logical_writes":
					assert.False(t, validatedMetrics["sqlserver.plan.avg_logical_writes"], "Found a duplicate in the metrics slice: sqlserver.plan.avg_logical_writes")
					validatedMetrics["sqlserver.plan.avg_logical_writes"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average logical page writes", ms.At(i).Description())
					assert.Equal(t, "{writes}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "sqlserver.plan.avg_worker_time_ms":
					assert.False(t, validatedMetrics["sqlserver.plan.avg_worker_time_ms"], "Found a duplicate in the metrics slice: sqlserver.plan.avg_worker_time_ms")
					validatedMetrics["sqlserver.plan.avg_worker_time_ms"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average CPU worker time", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "sqlserver.plan.execution_count":
					assert.False(t, validatedMetrics["sqlserver.plan.execution_count"], "Found a duplicate in the metrics slice: sqlserver.plan.execution_count")
					validatedMetrics["sqlserver.plan.execution_count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of times execution plan was executed", ms.At(i).Description())
					assert.Equal(t, "{executions}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.plan.total_elapsed_time_ms":
					assert.False(t, validatedMetrics["sqlserver.plan.total_elapsed_time_ms"], "Found a duplicate in the metrics slice: sqlserver.plan.total_elapsed_time_ms")
					validatedMetrics["sqlserver.plan.total_elapsed_time_ms"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Total elapsed time for all executions", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.security.principals.count":
					assert.False(t, validatedMetrics["sqlserver.security.principals.count"], "Found a duplicate in the metrics slice: sqlserver.security.principals.count")
					validatedMetrics["sqlserver.security.principals.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Server-level principals count", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.security.role_members.count":
					assert.False(t, validatedMetrics["sqlserver.security.role_members.count"], "Found a duplicate in the metrics slice: sqlserver.security.role_members.count")
					validatedMetrics["sqlserver.security.role_members.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Server role members count", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.slowquery.avg_cpu_time_ms":
					assert.False(t, validatedMetrics["sqlserver.slowquery.avg_cpu_time_ms"], "Found a duplicate in the metrics slice: sqlserver.slowquery.avg_cpu_time_ms")
					validatedMetrics["sqlserver.slowquery.avg_cpu_time_ms"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average CPU time for slow query", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("query_id")
					assert.True(t, ok)
					assert.Equal(t, "query_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("database_name")
					assert.True(t, ok)
					assert.Equal(t, "database_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query_text")
					assert.True(t, ok)
					assert.Equal(t, "query_text-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("last_execution_timestamp")
					assert.True(t, ok)
					assert.Equal(t, "last_execution_timestamp-val", attrVal.Str())
				case "sqlserver.slowquery.avg_disk_reads":
					assert.False(t, validatedMetrics["sqlserver.slowquery.avg_disk_reads"], "Found a duplicate in the metrics slice: sqlserver.slowquery.avg_disk_reads")
					validatedMetrics["sqlserver.slowquery.avg_disk_reads"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average physical disk reads", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("query_id")
					assert.True(t, ok)
					assert.Equal(t, "query_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("database_name")
					assert.True(t, ok)
					assert.Equal(t, "database_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query_text")
					assert.True(t, ok)
					assert.Equal(t, "query_text-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("last_execution_timestamp")
					assert.True(t, ok)
					assert.Equal(t, "last_execution_timestamp-val", attrVal.Str())
				case "sqlserver.slowquery.avg_disk_writes":
					assert.False(t, validatedMetrics["sqlserver.slowquery.avg_disk_writes"], "Found a duplicate in the metrics slice: sqlserver.slowquery.avg_disk_writes")
					validatedMetrics["sqlserver.slowquery.avg_disk_writes"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average physical disk writes", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("query_id")
					assert.True(t, ok)
					assert.Equal(t, "query_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("database_name")
					assert.True(t, ok)
					assert.Equal(t, "database_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query_text")
					assert.True(t, ok)
					assert.Equal(t, "query_text-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("last_execution_timestamp")
					assert.True(t, ok)
					assert.Equal(t, "last_execution_timestamp-val", attrVal.Str())
				case "sqlserver.slowquery.avg_rows_processed":
					assert.False(t, validatedMetrics["sqlserver.slowquery.avg_rows_processed"], "Found a duplicate in the metrics slice: sqlserver.slowquery.avg_rows_processed")
					validatedMetrics["sqlserver.slowquery.avg_rows_processed"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average number of rows processed", ms.At(i).Description())
					assert.Equal(t, "{rows}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("query_id")
					assert.True(t, ok)
					assert.Equal(t, "query_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("database_name")
					assert.True(t, ok)
					assert.Equal(t, "database_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query_text")
					assert.True(t, ok)
					assert.Equal(t, "query_text-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("last_execution_timestamp")
					assert.True(t, ok)
					assert.Equal(t, "last_execution_timestamp-val", attrVal.Str())
				case "sqlserver.slowquery.historical_avg_elapsed_time_ms":
					assert.False(t, validatedMetrics["sqlserver.slowquery.historical_avg_elapsed_time_ms"], "Found a duplicate in the metrics slice: sqlserver.slowquery.historical_avg_elapsed_time_ms")
					validatedMetrics["sqlserver.slowquery.historical_avg_elapsed_time_ms"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Historical average elapsed time since plan cached", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("query_id")
					assert.True(t, ok)
					assert.Equal(t, "query_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("database_name")
					assert.True(t, ok)
					assert.Equal(t, "database_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query_text")
					assert.True(t, ok)
					assert.Equal(t, "query_text-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("last_execution_timestamp")
					assert.True(t, ok)
					assert.Equal(t, "last_execution_timestamp-val", attrVal.Str())
				case "sqlserver.slowquery.historical_execution_count":
					assert.False(t, validatedMetrics["sqlserver.slowquery.historical_execution_count"], "Found a duplicate in the metrics slice: sqlserver.slowquery.historical_execution_count")
					validatedMetrics["sqlserver.slowquery.historical_execution_count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Total execution count since plan cached", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("query_id")
					assert.True(t, ok)
					assert.Equal(t, "query_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("database_name")
					assert.True(t, ok)
					assert.Equal(t, "database_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query_text")
					assert.True(t, ok)
					assert.Equal(t, "query_text-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("last_execution_timestamp")
					assert.True(t, ok)
					assert.Equal(t, "last_execution_timestamp-val", attrVal.Str())
				case "sqlserver.slowquery.interval_avg_elapsed_time_ms":
					assert.False(t, validatedMetrics["sqlserver.slowquery.interval_avg_elapsed_time_ms"], "Found a duplicate in the metrics slice: sqlserver.slowquery.interval_avg_elapsed_time_ms")
					validatedMetrics["sqlserver.slowquery.interval_avg_elapsed_time_ms"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Interval (delta) average elapsed time", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("query_id")
					assert.True(t, ok)
					assert.Equal(t, "query_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("database_name")
					assert.True(t, ok)
					assert.Equal(t, "database_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query_text")
					assert.True(t, ok)
					assert.Equal(t, "query_text-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("last_execution_timestamp")
					assert.True(t, ok)
					assert.Equal(t, "last_execution_timestamp-val", attrVal.Str())
				case "sqlserver.slowquery.interval_execution_count":
					assert.False(t, validatedMetrics["sqlserver.slowquery.interval_execution_count"], "Found a duplicate in the metrics slice: sqlserver.slowquery.interval_execution_count")
					validatedMetrics["sqlserver.slowquery.interval_execution_count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Execution count in collection interval (delta)", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("query_id")
					assert.True(t, ok)
					assert.Equal(t, "query_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("database_name")
					assert.True(t, ok)
					assert.Equal(t, "database_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query_text")
					assert.True(t, ok)
					assert.Equal(t, "query_text-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("last_execution_timestamp")
					assert.True(t, ok)
					assert.Equal(t, "last_execution_timestamp-val", attrVal.Str())
				case "sqlserver.slowquery.last_dop":
					assert.False(t, validatedMetrics["sqlserver.slowquery.last_dop"], "Found a duplicate in the metrics slice: sqlserver.slowquery.last_dop")
					validatedMetrics["sqlserver.slowquery.last_dop"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Degree of parallelism (DOP) used", ms.At(i).Description())
					assert.Equal(t, "{threads}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("query_id")
					assert.True(t, ok)
					assert.Equal(t, "query_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("database_name")
					assert.True(t, ok)
					assert.Equal(t, "database_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query_text")
					assert.True(t, ok)
					assert.Equal(t, "query_text-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("last_execution_timestamp")
					assert.True(t, ok)
					assert.Equal(t, "last_execution_timestamp-val", attrVal.Str())
				case "sqlserver.slowquery.last_grant_kb":
					assert.False(t, validatedMetrics["sqlserver.slowquery.last_grant_kb"], "Found a duplicate in the metrics slice: sqlserver.slowquery.last_grant_kb")
					validatedMetrics["sqlserver.slowquery.last_grant_kb"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Memory grant for query in KB", ms.At(i).Description())
					assert.Equal(t, "KBy", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("query_id")
					assert.True(t, ok)
					assert.Equal(t, "query_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("database_name")
					assert.True(t, ok)
					assert.Equal(t, "database_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query_text")
					assert.True(t, ok)
					assert.Equal(t, "query_text-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("last_execution_timestamp")
					assert.True(t, ok)
					assert.Equal(t, "last_execution_timestamp-val", attrVal.Str())
				case "sqlserver.slowquery.last_spills":
					assert.False(t, validatedMetrics["sqlserver.slowquery.last_spills"], "Found a duplicate in the metrics slice: sqlserver.slowquery.last_spills")
					validatedMetrics["sqlserver.slowquery.last_spills"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "TempDB spill pages", ms.At(i).Description())
					assert.Equal(t, "{pages}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("query_id")
					assert.True(t, ok)
					assert.Equal(t, "query_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("database_name")
					assert.True(t, ok)
					assert.Equal(t, "database_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query_text")
					assert.True(t, ok)
					assert.Equal(t, "query_text-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("last_execution_timestamp")
					assert.True(t, ok)
					assert.Equal(t, "last_execution_timestamp-val", attrVal.Str())
				case "sqlserver.tempdb.allocation_waits":
					assert.False(t, validatedMetrics["sqlserver.tempdb.allocation_waits"], "Found a duplicate in the metrics slice: sqlserver.tempdb.allocation_waits")
					validatedMetrics["sqlserver.tempdb.allocation_waits"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "TempDB allocation contention wait time", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.tempdb.current_waiters":
					assert.False(t, validatedMetrics["sqlserver.tempdb.current_waiters"], "Found a duplicate in the metrics slice: sqlserver.tempdb.current_waiters")
					validatedMetrics["sqlserver.tempdb.current_waiters"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Current tasks waiting on TempDB resources", ms.At(i).Description())
					assert.Equal(t, "{tasks}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.tempdb.data_file_count":
					assert.False(t, validatedMetrics["sqlserver.tempdb.data_file_count"], "Found a duplicate in the metrics slice: sqlserver.tempdb.data_file_count")
					validatedMetrics["sqlserver.tempdb.data_file_count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of TempDB data files", ms.At(i).Description())
					assert.Equal(t, "{files}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.tempdb.pagelatch_waits":
					assert.False(t, validatedMetrics["sqlserver.tempdb.pagelatch_waits"], "Found a duplicate in the metrics slice: sqlserver.tempdb.pagelatch_waits")
					validatedMetrics["sqlserver.tempdb.pagelatch_waits"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "TempDB page latch wait time", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.tempdb.total_size":
					assert.False(t, validatedMetrics["sqlserver.tempdb.total_size"], "Found a duplicate in the metrics slice: sqlserver.tempdb.total_size")
					validatedMetrics["sqlserver.tempdb.total_size"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Total TempDB size", ms.At(i).Description())
					assert.Equal(t, "MBy", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.threadpool.current_tasks":
					assert.False(t, validatedMetrics["sqlserver.threadpool.current_tasks"], "Found a duplicate in the metrics slice: sqlserver.threadpool.current_tasks")
					validatedMetrics["sqlserver.threadpool.current_tasks"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Current number of active tasks", ms.At(i).Description())
					assert.Equal(t, "{tasks}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.threadpool.max_workers":
					assert.False(t, validatedMetrics["sqlserver.threadpool.max_workers"], "Found a duplicate in the metrics slice: sqlserver.threadpool.max_workers")
					validatedMetrics["sqlserver.threadpool.max_workers"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Maximum configured worker threads", ms.At(i).Description())
					assert.Equal(t, "{threads}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.threadpool.runnable_tasks":
					assert.False(t, validatedMetrics["sqlserver.threadpool.runnable_tasks"], "Found a duplicate in the metrics slice: sqlserver.threadpool.runnable_tasks")
					validatedMetrics["sqlserver.threadpool.runnable_tasks"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Runnable tasks waiting for CPU", ms.At(i).Description())
					assert.Equal(t, "{tasks}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.threadpool.running_workers":
					assert.False(t, validatedMetrics["sqlserver.threadpool.running_workers"], "Found a duplicate in the metrics slice: sqlserver.threadpool.running_workers")
					validatedMetrics["sqlserver.threadpool.running_workers"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Currently executing worker threads", ms.At(i).Description())
					assert.Equal(t, "{threads}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.threadpool.utilization":
					assert.False(t, validatedMetrics["sqlserver.threadpool.utilization"], "Found a duplicate in the metrics slice: sqlserver.threadpool.utilization")
					validatedMetrics["sqlserver.threadpool.utilization"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Thread pool utilization percentage", ms.At(i).Description())
					assert.Equal(t, "%", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "sqlserver.threadpool.waiting_tasks":
					assert.False(t, validatedMetrics["sqlserver.threadpool.waiting_tasks"], "Found a duplicate in the metrics slice: sqlserver.threadpool.waiting_tasks")
					validatedMetrics["sqlserver.threadpool.waiting_tasks"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Tasks waiting for thread pool resources", ms.At(i).Description())
					assert.Equal(t, "{tasks}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.threadpool.work_queue_count":
					assert.False(t, validatedMetrics["sqlserver.threadpool.work_queue_count"], "Found a duplicate in the metrics slice: sqlserver.threadpool.work_queue_count")
					validatedMetrics["sqlserver.threadpool.work_queue_count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Work items queued for thread pool", ms.At(i).Description())
					assert.Equal(t, "{tasks}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.user_connections.authentication.failed":
					assert.False(t, validatedMetrics["sqlserver.user_connections.authentication.failed"], "Found a duplicate in the metrics slice: sqlserver.user_connections.authentication.failed")
					validatedMetrics["sqlserver.user_connections.authentication.failed"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of failed authentication attempts", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.user_connections.authentication.logins_per_sec":
					assert.False(t, validatedMetrics["sqlserver.user_connections.authentication.logins_per_sec"], "Found a duplicate in the metrics slice: sqlserver.user_connections.authentication.logins_per_sec")
					validatedMetrics["sqlserver.user_connections.authentication.logins_per_sec"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of logins per second", ms.At(i).Description())
					assert.Equal(t, "{logins}/s", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "sqlserver.user_connections.authentication.logouts_per_sec":
					assert.False(t, validatedMetrics["sqlserver.user_connections.authentication.logouts_per_sec"], "Found a duplicate in the metrics slice: sqlserver.user_connections.authentication.logouts_per_sec")
					validatedMetrics["sqlserver.user_connections.authentication.logouts_per_sec"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of logouts per second", ms.At(i).Description())
					assert.Equal(t, "{logouts}/s", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "sqlserver.user_connections.by_status":
					assert.False(t, validatedMetrics["sqlserver.user_connections.by_status"], "Found a duplicate in the metrics slice: sqlserver.user_connections.by_status")
					validatedMetrics["sqlserver.user_connections.by_status"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "User connections by status", ms.At(i).Description())
					assert.Equal(t, "{connections}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("connection_status")
					assert.True(t, ok)
					assert.Equal(t, "connection_status-val", attrVal.Str())
				case "sqlserver.user_connections.total":
					assert.False(t, validatedMetrics["sqlserver.user_connections.total"], "Found a duplicate in the metrics slice: sqlserver.user_connections.total")
					validatedMetrics["sqlserver.user_connections.total"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Total user connections", ms.At(i).Description())
					assert.Equal(t, "{connections}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "sqlserver.user_connections.utilization.active_ratio":
					assert.False(t, validatedMetrics["sqlserver.user_connections.utilization.active_ratio"], "Found a duplicate in the metrics slice: sqlserver.user_connections.utilization.active_ratio")
					validatedMetrics["sqlserver.user_connections.utilization.active_ratio"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Ratio of active to total connections", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "sqlserver.user_connections.utilization.efficiency":
					assert.False(t, validatedMetrics["sqlserver.user_connections.utilization.efficiency"], "Found a duplicate in the metrics slice: sqlserver.user_connections.utilization.efficiency")
					validatedMetrics["sqlserver.user_connections.utilization.efficiency"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Connection efficiency score", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "sqlserver.wait_stats.latch.wait_time":
					assert.False(t, validatedMetrics["sqlserver.wait_stats.latch.wait_time"], "Found a duplicate in the metrics slice: sqlserver.wait_stats.latch.wait_time")
					validatedMetrics["sqlserver.wait_stats.latch.wait_time"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Cumulative latch wait time", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("latch_class")
					assert.True(t, ok)
					assert.Equal(t, "latch_class-val", attrVal.Str())
				case "sqlserver.wait_stats.latch.waiting_tasks_count":
					assert.False(t, validatedMetrics["sqlserver.wait_stats.latch.waiting_tasks_count"], "Found a duplicate in the metrics slice: sqlserver.wait_stats.latch.waiting_tasks_count")
					validatedMetrics["sqlserver.wait_stats.latch.waiting_tasks_count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Number of tasks waiting for latch", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("latch_class")
					assert.True(t, ok)
					assert.Equal(t, "latch_class-val", attrVal.Str())
				case "sqlserver.wait_stats.wait_time":
					assert.False(t, validatedMetrics["sqlserver.wait_stats.wait_time"], "Found a duplicate in the metrics slice: sqlserver.wait_stats.wait_time")
					validatedMetrics["sqlserver.wait_stats.wait_time"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Cumulative wait time for wait type", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("wait_type")
					assert.True(t, ok)
					assert.Equal(t, "wait_type-val", attrVal.Str())
				case "sqlserver.wait_stats.waiting_tasks_count":
					assert.False(t, validatedMetrics["sqlserver.wait_stats.waiting_tasks_count"], "Found a duplicate in the metrics slice: sqlserver.wait_stats.waiting_tasks_count")
					validatedMetrics["sqlserver.wait_stats.waiting_tasks_count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Number of tasks waiting for this wait type", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("wait_type")
					assert.True(t, ok)
					assert.Equal(t, "wait_type-val", attrVal.Str())
				}
			}
		})
	}
}
